# Generated by Django 6.0.5 on 2026-06-29 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0015_producto_tipo'),
        ('compras', '0009_alter_recepciondetalle_ubicacion'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('terceros', '0013_cliente_celular_cliente_clave_cliente_contacto_and_more'),
        ('ventas', '0038_alter_cotizacion_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancos', to='nucleo.empresa')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'bancos',
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centro_costos', to='nucleo.empresa')),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costo',
                'db_table': 'centros_costo',
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='finanzas.banco')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='nucleo.moneda')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'db_table': 'cuentas_bancarias',
            },
        ),
        migrations.CreateModel(
            name='ConciliacionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones_bancarias', to='finanzas.cuentabancaria')),
            ],
            options={
                'verbose_name': 'Conciliacion Bancaria',
                'verbose_name_plural': 'Conciliaciones Bancarias',
                'db_table': 'conciliaciones_bancarias',
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cobro', models.DateField(auto_now=True)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta'), ('Cheque', 'Cheque')], default='Efectivo', max_length=30)),
                ('referencia', models.CharField(choices=[('SPEI', 'SPEI'), ('Cheque', 'Cheque'), ('Autorizacion TPV', 'Autorizacion TPV')], default='SPEI', max_length=30)),
                ('total_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='terceros.cliente')),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='finanzas.cuentabancaria')),
            ],
            options={
                'verbose_name': 'Cobro',
                'verbose_name_plural': 'Cobros',
                'db_table': 'cobros',
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_contables', to='nucleo.empresa')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'db_table': 'cuentas_contables',
            },
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('subototal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estatus', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Parcial'), ('Pagada', 'Pagada'), ('Cancelada', 'Cancelada'), ('Vencida', 'Vencida')], default='Pendiente', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar', to='terceros.cliente')),
            ],
            options={
                'verbose_name': 'Cuenta Por Cobrar',
                'verbose_name_plural': 'Cuentas Por Cobrar',
                'db_table': 'cuentas_por_cobrar',
            },
        ),
        migrations.CreateModel(
            name='CobroDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobro_detalles', to='finanzas.cobro')),
                ('cxc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobro_detalles', to='finanzas.cuentaporcobrar')),
            ],
            options={
                'verbose_name': 'Cobro Detalle',
                'verbose_name_plural': 'Cobros Detalle',
                'db_table': 'cobro_detalle',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='terceros.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='nucleo.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='nucleo.moneda')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='ventas.pedido')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='nucleo.sucursal')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'facturas',
            },
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar', to='finanzas.factura'),
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura_detalles', to='finanzas.factura')),
                ('pedido_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura_detalles', to='ventas.pedidodetalle')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura_detalles', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Factura Detalle',
                'verbose_name_plural': 'Facturas Detalle',
                'db_table': 'factura_detalle',
            },
        ),
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_proveedores', to='nucleo.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_proveedores', to='nucleo.moneda')),
                ('oc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_proveedores', to='compras.ordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_proveedores', to='terceros.proveedor')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_proveedores', to='compras.recepcion')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_proveedores', to='nucleo.sucursal')),
            ],
            options={
                'verbose_name': 'Factura Proveedor',
                'verbose_name_plural': 'Facturas Proveedor',
                'db_table': 'facturas_proveedor',
            },
        ),
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_pagar', to='terceros.proveedor')),
                ('factura_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_pagar', to='finanzas.facturaproveedor')),
            ],
            options={
                'verbose_name': 'Cuenta Por Pagar',
                'verbose_name_plural': 'Cuentas Por Pagar',
                'db_table': 'cuentas_por_pagar',
            },
        ),
        migrations.CreateModel(
            name='FacturaProveedorDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura_proveedor_detalles', to='finanzas.facturaproveedor')),
                ('oc_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura_proveedor_detalles', to='compras.ordencompradetalle')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura_proveedor_detalles', to='catalogo.producto')),
                ('recepcion_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura_proveedor_detalles', to='compras.recepciondetalle')),
            ],
            options={
                'verbose_name': 'Factura Proveedor Detalle',
                'verbose_name_plural': 'Facturas Proveedor Detalle',
                'db_table': 'factura_proveedor_detalle',
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_bancarios', to='finanzas.cobro')),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_bancarios', to='finanzas.cuentabancaria')),
            ],
            options={
                'verbose_name': 'Movimiento Bancario',
                'verbose_name_plural': 'Movimientos Bancarios',
                'db_table': 'movimientos_bancarios',
            },
        ),
        migrations.CreateModel(
            name='ConciliacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conciliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliacion_detalles', to='finanzas.conciliacionbancaria')),
                ('movimiento_bancario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliacion_detalles', to='finanzas.movimientobancario')),
            ],
            options={
                'verbose_name': 'Conciliacion Detalle',
                'verbose_name_plural': 'Conciliaciones Detalle',
                'db_table': 'conciliacion_detalle',
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota_creditos', to='terceros.cliente')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota_creditos', to='finanzas.factura')),
            ],
            options={
                'verbose_name': 'Nota Credito',
                'verbose_name_plural': 'Notas Creditos',
                'db_table': 'notas_creditos',
            },
        ),
        migrations.CreateModel(
            name='NotaCreditoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota_credito_detalles', to='finanzas.facturadetalle')),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota_credito_detalles', to='finanzas.notacredito')),
            ],
            options={
                'verbose_name': 'Nota Credito Detalle',
                'verbose_name_plural': 'Notas Creditos Detalle',
                'db_table': 'nota_credito_detalle',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finanzas.cuentabancaria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='terceros.proveedor')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
            },
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_bancarios', to='finanzas.pago'),
        ),
        migrations.CreateModel(
            name='PagoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cxp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_detalles', to='finanzas.cuentaporpagar')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_detalles', to='finanzas.pago')),
            ],
            options={
                'verbose_name': 'Pago Detalle',
                'verbose_name_plural': 'Pagos Detalle',
                'db_table': 'pago_detalle',
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='nucleo.empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='nucleo.sucursal')),
            ],
            options={
                'verbose_name': 'Poliza',
                'verbose_name_plural': 'Polizas',
                'db_table': 'polizas',
            },
        ),
        migrations.CreateModel(
            name='PolizaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poliza_detalles', to='finanzas.centrocosto')),
                ('cobro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poliza_detalles', to='finanzas.cobro')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poliza_detalles', to='finanzas.cuentacontable')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poliza_detalles', to='finanzas.factura')),
                ('factura_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poliza_detalles', to='finanzas.facturaproveedor')),
                ('movimiento_bancario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poliza_detalles', to='finanzas.movimientobancario')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poliza_detalles', to='finanzas.pago')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poliza_detalles', to='finanzas.poliza')),
            ],
            options={
                'verbose_name': 'Poliza Detalle',
                'verbose_name_plural': 'Polizas Detalle',
                'db_table': 'poliza_detalle',
            },
        ),
    ]
