# Generated by Django 6.0.5 on 2026-06-30 13:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentaporcobrar',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='cuentaporcobrar',
            name='impuesto',
        ),
        migrations.RemoveField(
            model_name='cuentaporcobrar',
            name='subototal',
        ),
        migrations.AddField(
            model_name='factura',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='factura',
            name='estatus',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Emitida', 'Emitida'), ('Cancelada', 'Cancelada')], default='Borrador', max_length=30),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='folio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='impuestos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='factura',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='serie_folio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='nucleo.seriefolio'),
        ),
        migrations.AddField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='factura',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
