# Generated by Django 6.0.5 on 2026-06-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_remove_cuentaporcobrar_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
