# Generated by Django 6.0.5 on 2026-07-06 16:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_factura_activo'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('terceros', '0013_cliente_celular_cliente_clave_cliente_contacto_and_more'),
        ('ventas', '0038_alter_cotizacion_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFactura',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_emision', models.DateField(blank=True, editable=False)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('folio', models.CharField(blank=True, max_length=30, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estatus', models.CharField(choices=[('Borrador', 'Borrador'), ('Emitida', 'Emitida'), ('Cancelada', 'Cancelada')], default='Borrador', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='terceros.cliente')),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.moneda')),
                ('pedido', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.pedido')),
                ('serie_folio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.seriefolio')),
                ('sucursal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.sucursal')),
            ],
            options={
                'verbose_name': 'historical Factura',
                'verbose_name_plural': 'historical Facturas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
