# Generated by Django 6.0.4 on 2026-07-10 22:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_historicalfactura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='swift',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='centrocosto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='centrocosto',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centrocosto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centrocosto',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cobro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cobro',
            name='estatus',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Aplicado', 'Aplicado'), ('Cancelado', 'Cancelado')], default='Aplicado', max_length=30),
        ),
        migrations.AddField(
            model_name='cobro',
            name='referencia_operacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cobro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cobrodetalle',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conciliacionbancaria',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='conciliacionbancaria',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='conciliacionbancaria',
            name='estatus',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Cerrada', 'Cerrada'), ('Cancelada', 'Cancelada')], default='Borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='conciliacionbancaria',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conciliacionbancaria',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conciliacionbancaria',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conciliacionbancaria',
            name='saldo_estado_cuenta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='conciliacionbancaria',
            name='saldo_libros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='conciliacionbancaria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='conciliaciondetalle',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='conciliaciondetalle',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='api_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='clabe',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='convenio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='fecha_apertura',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='numero_cliente',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='sucursal_bancaria',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='titular',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='ultima_sincronizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='acepta_movimientos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='cuenta_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.cuentacontable'),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='tipo',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Pasivo', 'Pasivo'), ('Capital', 'Capital'), ('Ingreso', 'Ingreso'), ('Gasto', 'Gasto'), ('Costo', 'Costo')], default='Activo', max_length=30),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='fecha_ultimo_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Parcial'), ('Pagada', 'Pagada'), ('Cancelada', 'Cancelada'), ('Vencida', 'Vencida')], default='Pendiente', max_length=30),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='fecha_emision',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='estatus',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Registrada', 'Registrada'), ('Cancelada', 'Cancelada')], default='Borrador', max_length=30),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='fecha_emision',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='folio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='impuestos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaproveedordetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturaproveedordetalle',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturaproveedordetalle',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturaproveedordetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturaproveedordetalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='facturaproveedordetalle',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='concepto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Conciliado', 'Conciliado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='fecha',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='fecha_aplicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='origen',
            field=models.CharField(choices=[('Manual', 'Manual'), ('SPEI', 'SPEI'), ('API', 'API'), ('CSV', 'CSV'), ('Conciliacion', 'Conciliacion')], default='Manual', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('Cargo', 'Cargo'), ('Abono', 'Abono')], default='Cargo', max_length=10),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='estatus',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Emitida', 'Emitida'), ('Cancelada', 'Cancelada')], default='Borrador', max_length=30),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='fecha_emision',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='folio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='impuestos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='notacreditodetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='notacreditodetalle',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='notacreditodetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='notacreditodetalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='notacreditodetalle',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pago',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='estatus',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Aplicado', 'Aplicado'), ('Cancelado', 'Cancelado')], default='Aplicado', max_length=30),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta'), ('Cheque', 'Cheque')], default='Transferencia', max_length=30),
        ),
        migrations.AddField(
            model_name='pago',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pago',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pagodetalle',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='pagodetalle',
            name='importe_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pagodetalle',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='finanzas.centrocosto'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='concepto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='estatus',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Pasivo', 'Pasivo'), ('Capital', 'Capital'), ('Ingreso', 'Ingreso'), ('Gasto', 'Gasto'), ('Costo', 'Costo')], default='Activo', max_length=30),
        ),
        migrations.AddField(
            model_name='poliza',
            name='fecha',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='folio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='folio_consecutivo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='tipo',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Pasivo', 'Pasivo'), ('Diario', 'Diario'), ('Ajuste', 'Ajuste'), ('Capital', 'Capital'), ('Ingreso', 'Ingreso'), ('Gasto', 'Gasto'), ('Costo', 'Costo')], default='Activo', max_length=30),
        ),
        migrations.AddField(
            model_name='poliza',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='polizadetalle',
            name='abono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='polizadetalle',
            name='cargo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='polizadetalle',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='polizadetalle',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='polizadetalle',
            name='referencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
