# Generated by Django 6.0.4 on 2026-07-14 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_banco_activo_banco_codigo_banco_created_at_and_more'),
        ('ventas', '0040_cotizacion_tipo_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='ventas.pedido'),
        ),
    ]
