# Generated by Django 6.0.5 on 2026-08-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_alter_factura_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
