# Generated by Django 6.0.7 on 2026-08-31 16:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_alter_cuentaporcobrar_fecha_emision_and_more'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conciliacionbancaria',
            name='diferencia',
        ),
        migrations.RemoveField(
            model_name='poliza',
            name='folio_consecutivo',
        ),
        migrations.AddField(
            model_name='cobro',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='nucleo.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='nucleo.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_pagar', to='nucleo.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='fecha_ultimo_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='nucleo.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia_operacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='fecha_cobro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='fecha_apertura',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='movimientobancario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='estatus',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Contabilizada', 'Contabilizada'), ('Cancelada', 'Cancelada')], default='Borrador', max_length=30),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='tipo',
            field=models.CharField(choices=[('Diario', 'Diario'), ('Ingreso', 'Ingreso'), ('Egreso', 'Egreso'), ('Ajuste', 'Ajuste')], default='Diario', max_length=30),
        ),
        migrations.AlterField(
            model_name='polizadetalle',
            name='centro_costo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poliza_detalles', to='finanzas.centrocosto'),
        ),
        migrations.AlterField(
            model_name='polizadetalle',
            name='cobro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poliza_detalles', to='finanzas.cobro'),
        ),
        migrations.AlterField(
            model_name='polizadetalle',
            name='cuenta_contable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poliza_detalles', to='finanzas.cuentacontable'),
        ),
        migrations.AlterField(
            model_name='polizadetalle',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poliza_detalles', to='finanzas.factura'),
        ),
        migrations.AlterField(
            model_name='polizadetalle',
            name='factura_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poliza_detalles', to='finanzas.facturaproveedor'),
        ),
        migrations.AlterField(
            model_name='polizadetalle',
            name='movimiento_bancario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poliza_detalles', to='finanzas.movimientobancario'),
        ),
        migrations.AlterField(
            model_name='polizadetalle',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poliza_detalles', to='finanzas.pago'),
        ),
        migrations.AlterField(
            model_name='polizadetalle',
            name='poliza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poliza_detalles', to='finanzas.poliza'),
        ),
        migrations.CreateModel(
            name='AlertaMora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuenta', models.CharField(choices=[('Cobrar', 'Cobrar'), ('Pagar', 'Pagar')], max_length=10)),
                ('dias_mora', models.PositiveIntegerField()),
                ('nivel', models.CharField(choices=[('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Critica', 'Critica')], max_length=20)),
                ('fecha_generada', models.DateTimeField(default=django.utils.timezone.now)),
                ('notificado', models.BooleanField(default=False)),
                ('fecha_notificado', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cuenta_por_cobrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='finanzas.cuentaporcobrar')),
                ('cuenta_por_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='finanzas.cuentaporpagar')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_mora', to='nucleo.empresa')),
            ],
            options={
                'verbose_name': 'Alerta de Mora',
                'verbose_name_plural': 'Alertas de Mora',
                'db_table': 'alertas_mora',
            },
        ),
    ]
