# Generated by Django 6.0.6 on 2026-09-01 16:17

import django.db.models.deletion
from django.db import migrations, models


def backfill_cxc_empresa(apps, schema_editor):
    CuentaPorCobrar = apps.get_model('finanzas', 'CuentaPorCobrar')
    Factura = apps.get_model('finanzas', 'Factura')
    db_alias = schema_editor.connection.alias

    factura_qs = (
        Factura.objects.using(db_alias)
        .filter(pk=models.OuterRef('factura_id'))
        .values('empresa_id')[:1]
    )
    (
        CuentaPorCobrar.objects.using(db_alias)
        .filter(empresa__isnull=True, factura__isnull=False)
        .update(empresa_id=models.Subquery(factura_qs))
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_remove_conciliacionbancaria_diferencia_and_more'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar', to='nucleo.empresa'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='folio_consecutivo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_cxc_empresa, noop_reverse),
    ]
