# Generated by Django 6.0.5 on 2026-09-04 22:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_cuentaporcobrar_empresa_poliza_folio_consecutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='fecha_cobro',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='fecha_apertura',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AlterField(
            model_name='movimientobancario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
