# Generated by Django 6.0.5 on 2026-09-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0010_alter_cobro_fecha_cobro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacredito',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
