# Generated by Django 6.0.5 on 2026-09-11 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_alter_notacredito_fecha_emision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polizadetalle',
            name='poliza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poliza_detalles', to='finanzas.poliza'),
        ),
    ]
