# Generated by Django 6.0.5 on 2026-09-11 15:40

from decimal import Decimal

from django.db import migrations, models


def remap_vencida_by_balance(apps, schema_editor):
    """``Vencida`` deja de ser un estatus persistido de la CxP.

    Ningún código ni migración la escribe: sólo pudo llegar desde la API o el
    admin. Sin filas es un no-op. Si las hay, cada una toma el estatus que le
    corresponde por saldo, con los mismos umbrales de PagoService, y cada cambio
    se imprime en la salida de la migración: nada se reasigna en silencio.
    """
    CuentaPorPagar = apps.get_model("finanzas", "CuentaPorPagar")
    rows = list(CuentaPorPagar.objects.filter(estatus="Vencida").only("pk", "total", "saldo"))
    for cxp in rows:
        saldo = Decimal(str(cxp.saldo or 0))
        total = Decimal(str(cxp.total or 0))
        if saldo <= Decimal("0.00"):
            estatus = "Pagada"
        elif saldo >= total - Decimal("0.01"):
            estatus = "Pendiente"
        else:
            estatus = "Parcial"
        CuentaPorPagar.objects.filter(pk=cxp.pk).update(estatus=estatus)
        print(f"  cuentas_por_pagar id={cxp.pk}: Vencida -> {estatus} (saldo={saldo}, total={total})")


def fail_on_duplicate_invoices(apps, schema_editor):
    """Detiene la migración si una factura de proveedor ya tiene varias CxP.

    El índice único fallaría igual, pero con un error de base de datos poco
    claro. No se borra ni se fusiona nada: qué cuenta conservar lo decide el
    operador.
    """
    CuentaPorPagar = apps.get_model("finanzas", "CuentaPorPagar")
    duplicates = (
        CuentaPorPagar.objects.values("factura_proveedor_id")
        .annotate(accounts=models.Count("id"))
        .filter(accounts__gt=1)
    )
    invoice_ids = sorted(row["factura_proveedor_id"] for row in duplicates)
    if invoice_ids:
        raise RuntimeError(
            "No se puede crear uq_cxp_factura_proveedor: estas facturas de proveedor "
            f"tienen más de una cuenta por pagar: {invoice_ids}. Resuélvalas a mano "
            "antes de migrar (SELECT factura_proveedor_id, count(*) FROM "
            "cuentas_por_pagar GROUP BY factura_proveedor_id HAVING count(*) > 1)."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0012_alter_polizadetalle_poliza'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('terceros', '0016_cliente_clientes_nombre_trgm_and_more'),
    ]

    operations = [
        migrations.RunPython(remap_vencida_by_balance, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Parcial'), ('Pagada', 'Pagada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=30),
        ),
        migrations.RunPython(fail_on_duplicate_invoices, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='cuentaporpagar',
            constraint=models.UniqueConstraint(fields=('factura_proveedor',), name='uq_cxp_factura_proveedor'),
        ),
    ]
