# Generated by Django 6.0.5 on 2026-09-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0013_cxp_unique_invoice_without_vencida'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cuentacontable',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo', ''), _negated=True), fields=('empresa', 'codigo'), name='uq_cuenta_contable_empresa_codigo'),
        ),
    ]
