# Generated by Django 6.0.5 on 2026-09-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0014_cuentacontable_uq_cuenta_contable_empresa_codigo'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='centrocosto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo', ''), _negated=True), fields=('empresa', 'codigo'), name='uq_centro_costo_empresa_codigo'),
        ),
    ]
