# Generated by Django 6.0.5 on 2026-09-17 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0015_centrocosto_uq_centro_costo_empresa_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas', to='finanzas.centrocosto'),
        ),
    ]
