# Generated by Django 6.0.5 on 2026-09-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0016_alter_poliza_centro_costo'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='centrocosto',
            name='uq_centro_costo_empresa_codigo',
        ),
        migrations.AddConstraint(
            model_name='centrocosto',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('codigo', ''), _negated=True), ('activo', True)), fields=('empresa', 'codigo'), name='uq_centro_costo_empresa_codigo'),
        ),
    ]
