# Generated by Django 6.0.7 on 2026-09-25 18:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0024_alter_productovariante_talla'),
        ('compras', '0015_ordencompra_motivo_cancelacion'),
        ('finanzas', '0017_remove_centrocosto_uq_centro_costo_empresa_codigo_and_more'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('terceros', '0016_cliente_clientes_nombre_trgm_and_more'),
        ('ventas', '0047_pedidodetalletalla_requiere_produccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertamora',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_mora', to='nucleo.empresa'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bancos', to='nucleo.empresa'),
        ),
        migrations.AlterField(
            model_name='centrocosto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centro_costos', to='nucleo.empresa'),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='terceros.cliente'),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='cuenta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='finanzas.cuentabancaria'),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='nucleo.empresa'),
        ),
        migrations.AlterField(
            model_name='cobrodetalle',
            name='cxc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobro_detalles', to='finanzas.cuentaporcobrar'),
        ),
        migrations.AlterField(
            model_name='conciliacionbancaria',
            name='cuenta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones_bancarias', to='finanzas.cuentabancaria'),
        ),
        migrations.AlterField(
            model_name='conciliaciondetalle',
            name='movimiento_bancario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacion_detalles', to='finanzas.movimientobancario'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancarias', to='finanzas.banco'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancarias', to='nucleo.empresa'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancarias', to='nucleo.moneda'),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_contables', to='nucleo.empresa'),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_cobrar', to='terceros.cliente'),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Parcial'), ('Pagada', 'Pagada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_cobrar', to='finanzas.factura'),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_pagar', to='nucleo.empresa'),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='factura_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_pagar', to='finanzas.facturaproveedor'),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_pagar', to='terceros.proveedor'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='terceros.cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='nucleo.empresa'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='factura',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='nucleo.moneda'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='serie_folio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='nucleo.seriefolio'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='nucleo.sucursal'),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='pedido_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factura_detalles', to='ventas.pedidodetalle'),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factura_detalles', to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_proveedores', to='nucleo.empresa'),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_proveedores', to='nucleo.moneda'),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='oc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_proveedores', to='compras.ordencompra'),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_proveedores', to='terceros.proveedor'),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_proveedores', to='compras.recepcion'),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_proveedores', to='nucleo.sucursal'),
        ),
        migrations.AlterField(
            model_name='facturaproveedordetalle',
            name='oc_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factura_proveedor_detalles', to='compras.ordencompradetalle'),
        ),
        migrations.AlterField(
            model_name='facturaproveedordetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factura_proveedor_detalles', to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='facturaproveedordetalle',
            name='recepcion_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factura_proveedor_detalles', to='compras.recepciondetalle'),
        ),
        migrations.AlterField(
            model_name='historicalfactura',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='movimientobancario',
            name='cobro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_bancarios', to='finanzas.cobro'),
        ),
        migrations.AlterField(
            model_name='movimientobancario',
            name='cuenta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_bancarios', to='finanzas.cuentabancaria'),
        ),
        migrations.AlterField(
            model_name='movimientobancario',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Conciliado', 'Conciliado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientobancario',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_bancarios', to='finanzas.pago'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nota_creditos', to='terceros.cliente'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nota_creditos', to='finanzas.factura'),
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='factura_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nota_credito_detalles', to='finanzas.facturadetalle'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cuenta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='finanzas.cuentabancaria'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='nucleo.empresa'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='terceros.proveedor'),
        ),
        migrations.AlterField(
            model_name='pagodetalle',
            name='cxp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pago_detalles', to='finanzas.cuentaporpagar'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='nucleo.empresa'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='nucleo.sucursal'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to=settings.AUTH_USER_MODEL),
        ),
    ]
