# Generated by Django 6.0.7 on 2026-10-02 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0019_syncfyuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncfyuser',
            options={'verbose_name': 'Syncfy user', 'verbose_name_plural': 'Syncfy users'},
        ),
        migrations.AlterModelTable(
            name='syncfyuser',
            table='syncfy_users',
        ),
    ]
