# Generated by Django 6.0.5 on 2026-10-05 13:26

import django.contrib.postgres.indexes
import django.db.models.functions.text
import nucleo.indices
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0020_alter_syncfyuser_options_alter_syncfyuser_table'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='factura',
            index=nucleo.indices.IndexSoloPostgres(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('folio'), name='text_pattern_ops'), name='facturas_folio_upper_like'),
        ),
    ]
