# Generated by Django 6.0.5 on 2026-10-02 22:15

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations, models

from nucleo.migration_operations import AddIndexSoloPostgres


# Índice de expresión ``UPPER(folio)`` para el ``istartswith`` del buscador global.
# Ver ``AddIndexSoloPostgres`` para el porqué de la operación propia.


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0020_alter_syncfyuser_options_alter_syncfyuser_table'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('terceros', '0017_indices_busqueda_upper'),
        ('ventas', '0048_indices_busqueda_upper'),
    ]

    operations = [
        AddIndexSoloPostgres(
            model_name='factura',
            index=models.Index(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('folio'), name='text_pattern_ops'), name='facturas_folio_upper_like'),
        ),
    ]
