# Generated by Django 6.0.6 on 2026-10-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0021_factura_folio_upper'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproveedor',
            name='pdf_adjunto',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='pdf_adjunto_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
