# Generated by Django 6.0.7 on 2026-10-06 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0022_facturaproveedor_pdf_adjunto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncfyWebhookNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('body_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'syncfy_webhook_notifications',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncfyWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True)),
                ('event_name', models.CharField(db_index=True, max_length=100)),
                ('event_version', models.CharField(blank=True, max_length=20)),
                ('event_at', models.DateTimeField(blank=True, null=True)),
                ('id_environment', models.CharField(blank=True, max_length=100)),
                ('id_external', models.CharField(blank=True, max_length=255)),
                ('id_user', models.CharField(blank=True, max_length=100)),
                ('id_credential', models.CharField(blank=True, db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='finanzas.syncfywebhooknotification')),
            ],
            options={
                'db_table': 'syncfy_webhook_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['event_name', 'id_credential'], name='syncfy_webh_event_n_2075ea_idx'), models.Index(fields=['event_name', 'created_at'], name='syncfy_webh_event_n_125d5c_idx')],
                'constraints': [models.UniqueConstraint(fields=('notification', 'event_id'), name='unique_syncfy_event_per_notification')],
            },
        ),
    ]
