# Generated by Django 6.0.7 on 2026-10-07 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0023_syncfywebhooknotification_syncfywebhookevent'),
        ('ventas', '0048_indices_busqueda_upper'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadetalle',
            name='pedido_detalle_talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factura_detalles', to='ventas.pedidodetalletalla'),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='porcentaje_impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
