# Generated by Django 6.0.7 on 2026-10-08 22:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0024_factura_detalle_por_talla'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='poliza_reversa_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversas', to='finanzas.poliza'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddConstraint(
            model_name='poliza',
            constraint=models.UniqueConstraint(condition=models.Q(('poliza_reversa_de__isnull', False)), fields=('poliza_reversa_de',), name='uq_poliza_reversa_de'),
        ),
    ]
