# Generated by Django 6.0.7 on 2026-10-08 23:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0025_poliza_cimientos'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancarias', to='finanzas.cuentacontable'),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='cuenta_contable_contrapartida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_bancarios', to='finanzas.cuentacontable'),
        ),
        migrations.CreateModel(
            name='ParametrosContabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contabilizacion_automatica', models.BooleanField(default=False)),
                ('fecha_inicio_contabilizacion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_contabilidad', to='nucleo.empresa')),
            ],
            options={
                'verbose_name': 'Parámetros de Contabilidad',
                'verbose_name_plural': 'Parámetros de Contabilidad',
                'db_table': 'parametros_contabilidad',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('Clientes', 'Clientes (cuentas por cobrar)'), ('IngresoVentas', 'Ingresos por ventas'), ('DescuentoSobreVentas', 'Descuentos sobre ventas'), ('DevolucionesSobreVentas', 'Devoluciones y rebajas sobre ventas'), ('IvaTrasladado', 'IVA trasladado'), ('Proveedores', 'Proveedores (cuentas por pagar)'), ('ComprasInventario', 'Compras / inventario'), ('GastosCompra', 'Gastos por compras'), ('DescuentoSobreCompras', 'Descuentos sobre compras'), ('IvaAcreditable', 'IVA acreditable'), ('Bancos', 'Bancos (cuenta por omisión)'), ('ContrapartidaMovimientoCargo', 'Contrapartida de retiro sin documento'), ('ContrapartidaMovimientoAbono', 'Contrapartida de depósito sin documento'), ('PercepcionNomina', 'Percepción de nómina'), ('DeduccionNomina', 'Deducción de nómina'), ('NominaPorPagar', 'Nómina por pagar')], max_length=40)),
                ('clave', models.CharField(blank=True, default='', max_length=30)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_contables', to='finanzas.centrocosto')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_contables', to='finanzas.cuentacontable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_contables', to='nucleo.empresa')),
            ],
            options={
                'verbose_name': 'Configuración Contable',
                'verbose_name_plural': 'Configuraciones Contables',
                'db_table': 'configuraciones_contables',
                'indexes': [models.Index(fields=['empresa', 'concepto'], name='configuraci_empresa_4c7045_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('empresa', 'concepto', 'clave'), name='uq_config_contable_empresa_concepto_clave')],
            },
        ),
    ]
