# Generated by Django 6.0.7 on 2026-10-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0026_plan_contable'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('terceros', '0017_indices_busqueda_upper'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cuentaporcobrar',
            constraint=models.UniqueConstraint(fields=('factura',), name='uq_cxc_factura'),
        ),
    ]
