# Generated by Django 5.2 on 2026-02-03 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0002_satformapago_satmetodopago_satregimenfiscal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaEvento',
            fields=[
                ('id_evento', models.BigAutoField(primary_key=True, serialize=False)),
                ('modulo', models.CharField(max_length=60)),
                ('accion', models.CharField(max_length=30)),
                ('tabla', models.CharField(blank=True, max_length=80, null=True)),
                ('id_registro', models.CharField(blank=True, max_length=80, null=True)),
                ('antes_json', models.JSONField(blank=True, null=True)),
                ('despues_json', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='nucleo.empresa')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'db_table': 'auditoria_eventos',
            },
        ),
    ]
