# Generated by Django 5.2 on 2026-02-03 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaevento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditoriaevento',
            index=models.Index(fields=['empresa', 'created_at'], name='auditoria_e_empresa_08c86e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaevento',
            index=models.Index(fields=['modulo', 'accion'], name='auditoria_e_modulo_f4cb97_idx'),
        ),
    ]
