# Generated by Django 5.2 on 2026-02-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditoriaEvento',
        ),
    ]
