# Generated by Django 6.0.2 on 2026-02-25 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0003_delete_auditoriaevento'),
        ('nucleo', '0008_remove_departamento_departament_empresa_a3883d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaEvento',
            fields=[
                ('id_evento', models.BigAutoField(primary_key=True, serialize=False)),
                ('modulo', models.CharField(max_length=60)),
                ('accion', models.CharField(max_length=30)),
                ('tabla', models.CharField(blank=True, max_length=80, null=True)),
                ('id_registro', models.CharField(blank=True, max_length=80, null=True)),
                ('antes_json', models.JSONField(blank=True, null=True)),
                ('despues_json', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='nucleo.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'db_table': 'auditoria_eventos',
                'indexes': [models.Index(fields=['empresa', 'created_at'], name='auditoria_e_empresa_08c86e_idx'), models.Index(fields=['modulo', 'accion'], name='auditoria_e_modulo_f4cb97_idx')],
            },
        ),
    ]
