# Generated by Django 6.0.2 on 2026-02-13 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0008_remove_departamento_departament_empresa_a3883d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo Producto',
                'verbose_name_plural': 'Tipos Producto',
                'db_table': 'tipo_producto',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_producto', to='nucleo.empresa')),
            ],
            options={
                'verbose_name': 'Categoria Producto',
                'verbose_name_plural': 'Categorias Producto',
                'db_table': 'categorias_producto',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='catalogo.categoriaproducto')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='nucleo.empresa')),
                ('id_impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='nucleo.impuesto')),
                ('id_sat_prodserv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='nucleo.satclaveprodserv')),
                ('id_sat_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='nucleo.satclaveunidad')),
                ('id_unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='nucleo.unidadmedida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
    ]
