# Generated by Django 6.0.2 on 2026-02-13 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('nucleo', '0008_remove_departamento_departament_empresa_a3883d_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriaproducto',
            old_name='id_empresa',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_categoria_producto',
            new_name='categoria_producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_empresa',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_impuesto',
            new_name='impuesto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_sat_prodserv',
            new_name='sat_prodserv',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_unidad_medida',
            new_name='unidad_medida',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_sat_unidad',
        ),
        migrations.AddField(
            model_name='producto',
            name='sat_unidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='nucleo.satclaveunidad'),
            preserve_default=False,
        ),
    ]
