# Generated by Django 6.0.2 on 2026-03-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_color_talla_categoriaproducto_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
