# Generated by Django 5.2 on 2026-04-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_producto_precio_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, default='', help_text='Stock Keeping Unit (Código interno)', max_length=50),
        ),
    ]
