# Generated by Django 6.0.4 on 2026-04-20 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_producto_sku'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='sku',
        ),
        migrations.CreateModel(
            name='VarianteProductoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variantes_produccion', to='catalogo.color')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes_produccion', to='nucleo.empresa')),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes_produccion', to='produccion.ordenproduccion')),
                ('producto_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variantes_produccion', to='catalogo.producto')),
                ('talla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variantes_produccion', to='catalogo.talla')),
            ],
        ),
    ]
