# Generated by Django 6.0.4 on 2026-04-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_remove_producto_sku_varianteproductoproduccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varianteproductoproduccion',
            options={'verbose_name': 'Variante Producto Produccion', 'verbose_name_plural': 'Variantes Producto Produccion'},
        ),
        migrations.AlterModelTable(
            name='varianteproductoproduccion',
            table='variantes_producto_produccion',
        ),
    ]
