# Generated by Django 6.0.4 on 2026-04-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_varianteproductoproduccion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='codigo',
            field=models.CharField(default='AZU', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='codigo',
            field=models.CharField(max_length=3),
        ),
    ]
