# Generated by Django 6.0.4 on 2026-04-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_color_codigo_alter_categoriaproducto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cod_proscai',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
