# Generated by Django 6.0.4 on 2026-05-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_producto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productovariante',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
