# Generated by Django 6.0.5 on 2026-06-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_productovariante_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
    ]
