# Generated by Django 6.0.7 on 2026-09-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_historicalcategoriaproducto_historicalproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='codigo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
