# Generated by Django 6.0.7 on 2026-09-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_alter_historicalproducto_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductovariante',
            name='cod_proscai',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productovariante',
            name='cod_proscai',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
