# Generated by Django 6.0.6 on 2026-09-18 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0020_fusionar_talla_2xc_2xch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProductoTalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tallas_permitidas', to='catalogo.categoriaproducto')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_permitidas', to='catalogo.talla')),
            ],
            options={
                'verbose_name': 'Talla por Categoria',
                'verbose_name_plural': 'Tallas por Categoria',
                'db_table': 'categorias_producto_tallas',
            },
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='tallas',
            field=models.ManyToManyField(blank=True, related_name='categorias_producto', through='catalogo.CategoriaProductoTalla', to='catalogo.talla'),
        ),
        migrations.AddConstraint(
            model_name='categoriaproductotalla',
            constraint=models.UniqueConstraint(fields=('categoria_producto', 'talla'), name='uq_categoria_producto_talla'),
        ),
    ]
