# Generated by Django 6.0.4 on 2026-09-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0021_categoriaproductotalla_categoriaproducto_tallas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='pantone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcolor',
            name='pantone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
