# Generated by Django 6.0.4 on 2026-09-21 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0022_color_pantone_historicalcolor_pantone'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_producto', to='nucleo.unidadmedida'),
        ),
        migrations.AddField(
            model_name='historicalcategoriaproducto',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nucleo.unidadmedida'),
        ),
    ]
