# Generated by Django 6.0.4 on 2026-09-21 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0023_categoriaproducto_unidad_medida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productovariante',
            name='talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.talla'),
        ),
    ]
