# Generated by Django 6.0.5 on 2026-10-02 22:23

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations, models

from nucleo.migration_operations import AddIndexSoloPostgres


# Índices de expresión ``UPPER(col)`` para el buscador global: btree
# ``text_pattern_ops`` para el prefijo de ``sku`` y GIN trigram para los nombres.
# Ver ``AddIndexSoloPostgres`` para el porqué de la operación propia.


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0024_alter_productovariante_talla'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
    ]

    operations = [
        AddIndexSoloPostgres(
            model_name='producto',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('nombre'), name='gin_trgm_ops'), name='productos_nombre_upper_trgm'),
        ),
        AddIndexSoloPostgres(
            model_name='productovariante',
            index=models.Index(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('sku'), name='text_pattern_ops'), name='variantes_sku_upper_like'),
        ),
        AddIndexSoloPostgres(
            model_name='productovariante',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('nombre'), name='gin_trgm_ops'), name='variantes_nombre_upper_trgm'),
        ),
    ]
