# Generated by Django 6.0.5 on 2026-10-05 13:26

import django.contrib.postgres.indexes
import django.db.models.functions.text
import nucleo.indices
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0024_alter_productovariante_talla'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='producto',
            index=nucleo.indices.GinIndexSoloPostgres(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('nombre'), name='gin_trgm_ops'), name='productos_nombre_upper_trgm'),
        ),
        migrations.AddIndex(
            model_name='productovariante',
            index=nucleo.indices.IndexSoloPostgres(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('sku'), name='text_pattern_ops'), name='variantes_sku_upper_like'),
        ),
        migrations.AddIndex(
            model_name='productovariante',
            index=nucleo.indices.GinIndexSoloPostgres(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('nombre'), name='gin_trgm_ops'), name='variantes_nombre_upper_trgm'),
        ),
    ]
