# Generated by Django 6.0.7 on 2026-10-09 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0025_indices_busqueda_upper'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('produccion', '0038_orden_corte_manga_folio_upper'),
        ('ventas', '0048_indices_busqueda_upper'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvarianteproductoproduccion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalvarianteproductoproduccion',
            name='aplica_catalogo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalvarianteproductoproduccion',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='historicalvarianteproductoproduccion',
            name='pedido_detalle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.pedidodetalle'),
        ),
        migrations.AddField(
            model_name='historicalvarianteproductoproduccion',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='varianteproductoproduccion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='varianteproductoproduccion',
            name='aplica_catalogo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='varianteproductoproduccion',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='varianteproductoproduccion',
            name='pedido_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variantes_produccion', to='ventas.pedidodetalle'),
        ),
        migrations.AddField(
            model_name='varianteproductoproduccion',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='varianteproductoproduccion',
            name='op',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variantes_produccion', to='produccion.ordenproduccion'),
        ),
        migrations.AddConstraint(
            model_name='varianteproductoproduccion',
            constraint=models.UniqueConstraint(fields=('pedido_detalle', 'talla'), name='uq_variante_produccion_pedido_detalle_talla'),
        ),
    ]
