"""
Django settings for ERP project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS defined in environment
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'widget_tweaks',
    'nucleo',
    'seguridad',
    'usuarios',
    'auditoria',
    'axes',
    'inventarios',
    'catalogo',
    'terceros',
    'ventas',
    'compras',
    'produccion',
    'drf_spectacular',
]

AUTH_USER_MODEL = "usuarios.Usuario"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
    'nucleo.middleware.APILoggingMiddleware',
    'nucleo.middleware.NoCacheMiddleware',
]

ROOT_URLCONF = 'ERP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ERP.wsgi.application'

# =========================
# LOGS DIRECTORY
# =========================
# Directorio base donde se guardan los archivos de logs que consulta Auditoría.
LOGS_DIR = BASE_DIR / 'logs'
try:
    os.makedirs(LOGS_DIR, exist_ok=True)
except OSError:
    LOGS_DIR = Path('/tmp') / 'logs'
    os.makedirs(LOGS_DIR, exist_ok=True)


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = config('DATABASE_URL', default='')
SUPABASE_DATABASE_URL = config('SUPABASE_DATABASE_URL', default='')
REMOTE_DATABASE_URL = DATABASE_URL or SUPABASE_DATABASE_URL

ENVIRONMENT = config('ENVIRONMENT', default='development')
IS_VERCEL = os.environ.get('VERCEL') == '1'
USE_REMOTE_DB = config('USE_REMOTE_DB', default=(IS_VERCEL or ENVIRONMENT.lower() == 'production'), cast=bool)

LOCAL_POSTGRES_DB_HOST = config('LOCAL_POSTGRES_DB_HOST', default='127.0.0.1')
LOCAL_POSTGRES_DB_USER = config('LOCAL_POSTGRES_DB_USER', default='postgres')
LEGACY_POSTGRESQL_DB_PASSWORD = config('POSTGRESQL_DB_PASSWORD', default='')
LOCAL_POSTGRES_DB_PASSWORD = config('LOCAL_POSTGRES_DB_PASSWORD', default=LEGACY_POSTGRESQL_DB_PASSWORD)
LOCAL_POSTGRES_DB_NAME = config('LOCAL_POSTGRES_DB_NAME', default='erp')
LOCAL_POSTGRES_DB_PORT = config('LOCAL_POSTGRES_DB_PORT', default='5432')
LOCAL_POSTGRES_SSLMODE = config('LOCAL_POSTGRES_SSLMODE', default='disable')

if USE_REMOTE_DB and REMOTE_DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            REMOTE_DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': LOCAL_POSTGRES_DB_NAME,
            'USER': LOCAL_POSTGRES_DB_USER,
            'PASSWORD': LOCAL_POSTGRES_DB_PASSWORD,
            'HOST': LOCAL_POSTGRES_DB_HOST,
            'PORT': LOCAL_POSTGRES_DB_PORT,
            'DISABLE_SERVER_SIDE_CURSORS': True,
            'OPTIONS': {
                'sslmode': LOCAL_POSTGRES_SSLMODE,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =========================
# DJANGO REST FRAMEWORK
# =========================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'usuarios.backends.BearerTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Núcleo ERP API',
    'DESCRIPTION': 'Documentación interactiva de la API para el sistema ERP.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Opcional: Para autenticación en Swagger UI
    'COMPONENT_SPLIT_REQUEST': True
}

# =========================
# CORS HEADERS
# =========================
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = config('CORS_ALLOW_CREDENTIALS', default=True, cast=bool)
CORS_ALLOWED_ORIGINS = [o for o in config('CORS_ALLOWED_ORIGINS', default='http://localhost:3000,https://localhost:3000').split(',') if o]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^https://.*\.onrender\.com$',
    r'^https://.*\.vercel\.app$',
]
CORS_URLS_REGEX = r'^/api/.*$'

CSRF_TRUSTED_ORIGINS = [o for o in config('CSRF_TRUSTED_ORIGINS', default='https://*.onrender.com,https://*.vercel.app,https://localhost:3000,http://localhost:3000').split(',') if o]

# =========================
# AUTH SETTINGS
# =========================
LOGIN_REDIRECT_URL = 'nucleo:dashboard'
LOGOUT_REDIRECT_URL = '/'

# =========================
# AXES SETTINGS
# =========================
AUTHENTICATION_BACKENDS = [
    # AxesBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    'axes.backends.AxesBackend',
    # Custom Email Backend
    'usuarios.backends.EmailBackend',
    # Django ModelBackend is the default authentication backend.
    'django.contrib.auth.backends.ModelBackend',
]

AXES_FAILURE_LIMIT = 5  # Numero de intentos fallidos antes de bloquear
AXES_COOLOFF_TIME = 1   # Tiempo de espera en horas
AXES_LOCKOUT_TEMPLATE = '403.html' # Usar nuestro template 403 o uno especifico para lockout
AXES_USERNAME_FORM_FIELD = 'email'  # Indicar a Axes que usamos 'email' como identificador

# =========================
# SECURITY HARDENING (Production Recommendations)
# =========================
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# SSL and Cookies (Controlled by env vars)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)

# HSTS Settings (Only enable if SSL is active and stable)
if SECURE_SSL_REDIRECT:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# =========================
# LOGGING CONFIGURATION
# =========================

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'api_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'api.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'nucleo': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'api_logger': {
            'handlers': ['api_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
