# Generated by Django 4.2.27 on 2026-01-28 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.SlugField(max_length=32, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('timezone', models.CharField(default='America/Mexico_City', max_length=64)),
                ('idioma', models.CharField(default='es-MX', max_length=16)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tasa', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('tipo', models.CharField(choices=[('trasladado', 'Trasladado'), ('retencion', 'Retención')], default='trasladado', max_length=20)),
                ('estatus', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'db_table': 'impuestos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iso', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('simbolo', models.CharField(blank=True, max_length=10, null=True)),
                ('decimales', models.PositiveSmallIntegerField(default=2)),
                ('estatus', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'db_table': 'monedas',
                'ordering': ['codigo_iso'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('estatus', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidades_medida',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion_linea1', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_linea2', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('cp', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='nucleo.empresa')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='SerieFolio',
            fields=[
                ('id_serie_folio', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=20)),
                ('folio_actual', models.PositiveIntegerField(default=0)),
                ('folio_inicial', models.PositiveIntegerField(blank=True, null=True)),
                ('folio_final', models.PositiveIntegerField(blank=True, null=True)),
                ('prefijo', models.CharField(blank=True, max_length=20, null=True)),
                ('sufijo', models.CharField(blank=True, max_length=20, null=True)),
                ('relleno_ceros', models.PositiveSmallIntegerField(default=6)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_folios', to='nucleo.empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_folios', to='nucleo.sucursal')),
            ],
            options={
                'verbose_name': 'Serie/Folio',
                'verbose_name_plural': 'Series/Folios',
                'db_table': 'series_folios',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='moneda_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='nucleo.moneda'),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='nucleo.empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='nucleo.sucursal')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
            },
        ),
        migrations.AddIndex(
            model_name='sucursal',
            index=models.Index(fields=['empresa', 'codigo'], name='sucursales_empresa_91d88c_idx'),
        ),
        migrations.AddIndex(
            model_name='sucursal',
            index=models.Index(fields=['empresa', 'estatus'], name='sucursales_empresa_7e5a32_idx'),
        ),
        migrations.AddConstraint(
            model_name='sucursal',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_sucursal_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='sucursal',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='uq_sucursal_empresa_nombre'),
        ),
        migrations.AddIndex(
            model_name='seriefolio',
            index=models.Index(fields=['empresa', 'tipo_documento'], name='series_foli_empresa_96365c_idx'),
        ),
        migrations.AddIndex(
            model_name='seriefolio',
            index=models.Index(fields=['sucursal', 'tipo_documento'], name='series_foli_sucursa_567e12_idx'),
        ),
        migrations.AddConstraint(
            model_name='seriefolio',
            constraint=models.UniqueConstraint(fields=('sucursal', 'tipo_documento', 'serie'), name='uq_serie_folio_sucursal_tipo_serie'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['codigo'], name='empresas_codigo_814239_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['estatus'], name='empresas_estatus_11c805_idx'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['empresa'], name='departament_empresa_a3883d_idx'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['sucursal'], name='departament_sucursa_66fd5d_idx'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['empresa', 'estatus'], name='departament_empresa_4c7874_idx'),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(fields=('sucursal', 'codigo'), name='uq_departamento_sucursal_codigo'),
        ),
    ]
