# Generated by Django 5.2 on 2026-02-03 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatFormaPago',
            fields=[
                ('id_sat_forma_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('bancarizado', models.BooleanField(default=False)),
                ('estatus', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'SAT Forma de Pago',
                'verbose_name_plural': 'SAT Formas de Pago',
                'db_table': 'sat_forma_pago',
            },
        ),
        migrations.CreateModel(
            name='SatMetodoPago',
            fields=[
                ('id_sat_metodo_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('estatus', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'SAT Método de Pago',
                'verbose_name_plural': 'SAT Métodos de Pago',
                'db_table': 'sat_metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='SatRegimenFiscal',
            fields=[
                ('id_sat_regimen_fiscal', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('aplica_fisica', models.BooleanField(default=False)),
                ('aplica_moral', models.BooleanField(default=False)),
                ('estatus', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'SAT Régimen Fiscal',
                'verbose_name_plural': 'SAT Regímenes Fiscales',
                'db_table': 'sat_regimen_fiscal',
            },
        ),
        migrations.CreateModel(
            name='SatTipoRelacion',
            fields=[
                ('id_sat_tipo_relacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('estatus', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'SAT Tipo Relación',
                'verbose_name_plural': 'SAT Tipos Relación',
                'db_table': 'sat_tipo_relacion',
            },
        ),
        migrations.CreateModel(
            name='SatUsoCfdi',
            fields=[
                ('id_sat_uso_cfdi', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('aplica_fisica', models.BooleanField(default=False)),
                ('aplica_moral', models.BooleanField(default=False)),
                ('estatus', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'SAT Uso CFDI',
                'verbose_name_plural': 'SAT Usos CFDI',
                'db_table': 'sat_uso_cfdi',
            },
        ),
        migrations.CreateModel(
            name='EmpresaSatConfig',
            fields=[
                ('id_empresa_sat_config', models.BigAutoField(primary_key=True, serialize=False)),
                ('certificado_sello_digital', models.TextField(blank=True, null=True)),
                ('llave_privada', models.TextField(blank=True, null=True)),
                ('password_llave', models.CharField(blank=True, max_length=255, null=True)),
                ('no_certificado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sat_config', to='nucleo.empresa')),
                ('regimen_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas_config', to='nucleo.satregimenfiscal')),
            ],
            options={
                'verbose_name': 'Configuración SAT Empresa',
                'verbose_name_plural': 'Configuraciones SAT Empresa',
                'db_table': 'empresa_sat_config',
            },
        ),
    ]
