# Generated by Django 5.2 on 2026-02-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_satformapago_satmetodopago_satregimenfiscal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatClaveProdServ',
            fields=[
                ('id_sat_prodserv', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('estatus', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'SAT Clave Prod/Serv',
                'verbose_name_plural': 'SAT Claves Prod/Serv',
                'db_table': 'sat_clave_prodserv',
            },
        ),
        migrations.CreateModel(
            name='SatClaveUnidad',
            fields=[
                ('id_sat_unidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('estatus', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'SAT Clave Unidad',
                'verbose_name_plural': 'SAT Claves Unidad',
                'db_table': 'sat_clave_unidad',
            },
        ),
        migrations.DeleteModel(
            name='SatTipoRelacion',
        ),
    ]
