# Generated by Django 6.0.2 on 2026-02-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_satclaveprodserv_satclaveunidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresasatconfig',
            name='certificado_sello_digital',
        ),
        migrations.RemoveField(
            model_name='empresasatconfig',
            name='llave_privada',
        ),
        migrations.AddField(
            model_name='empresasatconfig',
            name='mensaje_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresasatconfig',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
