# Generated by Django 6.0.2 on 2026-02-05 14:55

import nucleo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_remove_empresasatconfig_certificado_sello_digital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresasatconfig',
            name='archivo_cer',
            field=models.FileField(blank=True, help_text='Certificado (.cer)', null=True, upload_to=nucleo.models.get_upload_path_cer),
        ),
        migrations.AddField(
            model_name='empresasatconfig',
            name='archivo_key',
            field=models.FileField(blank=True, help_text='Llave Privada (.key)', null=True, upload_to=nucleo.models.get_upload_path_key),
        ),
        migrations.AddField(
            model_name='empresasatconfig',
            name='certificado_pem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresasatconfig',
            name='llave_privada_pem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
