# Generated by Django 6.0.2 on 2026-02-05 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_empresasatconfig_archivo_cer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresasatconfig',
            name='regimen_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_config', to='nucleo.satregimenfiscal'),
        ),
    ]
