# Generated by Django 6.0.2 on 2026-02-11 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_alter_empresasatconfig_regimen_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monedas_privadas', to='nucleo.empresa'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='codigo_iso',
            field=models.CharField(max_length=3),
        ),
        migrations.AddConstraint(
            model_name='moneda',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_iso'), name='unique_moneda_empresa'),
        ),
    ]
