# Generated by Django 6.0.2 on 2026-02-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_moneda_empresa_alter_moneda_codigo_iso_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='departamento',
            name='departament_empresa_a3883d_idx',
        ),
        migrations.RemoveIndex(
            model_name='departamento',
            name='departament_sucursa_66fd5d_idx',
        ),
    ]
