# Generated by Django 6.0.2 on 2026-02-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_remove_departamento_departament_empresa_a3883d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriefolio',
            name='incluir_anio',
            field=models.BooleanField(default=False, help_text='Incluir el año al final del folio (ej: -24)'),
        ),
        migrations.AddField(
            model_name='seriefolio',
            name='reiniciar_anual',
            field=models.BooleanField(default=False, help_text='Reiniciar el consecutivo al cambiar de año'),
        ),
        migrations.AddField(
            model_name='seriefolio',
            name='separador',
            field=models.CharField(blank=True, default='-', help_text='Caracter entre serie, folio y año', max_length=5),
        ),
        migrations.AddField(
            model_name='seriefolio',
            name='ultimo_anio',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Último año registrado (2 dígitos)', null=True),
        ),
        migrations.AlterField(
            model_name='seriefolio',
            name='relleno_ceros',
            field=models.PositiveSmallIntegerField(default=6, help_text='Ceros a la izquierda. 0 para desactivar.'),
        ),
    ]
