# Generated by Django 6.0.2 on 2026-03-09 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0009_seriefolio_incluir_anio_seriefolio_reiniciar_anual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='nucleo.status'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='nucleo.status'),
        ),
        migrations.AddField(
            model_name='impuesto',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='nucleo.status'),
        ),
        migrations.AddField(
            model_name='moneda',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='monedas', to='nucleo.status'),
        ),
        migrations.AddField(
            model_name='satclaveprodserv',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sat_clave_prodserv', to='nucleo.status'),
        ),
        migrations.AddField(
            model_name='satclaveunidad',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sat_clave_unidad', to='nucleo.status'),
        ),
        migrations.AddField(
            model_name='satformapago',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sat_forma_pago', to='nucleo.status'),
        ),
        migrations.AddField(
            model_name='satmetodopago',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sat_metodo_pago', to='nucleo.status'),
        ),
        migrations.AddField(
            model_name='satregimenfiscal',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sat_regimen_fiscal', to='nucleo.status'),
        ),
        migrations.AddField(
            model_name='satusocfdi',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sat_uso_cfdi', to='nucleo.status'),
        ),
        migrations.AddField(
            model_name='seriefolio',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='series_folios', to='nucleo.status'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='nucleo.status'),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unidades_medida', to='nucleo.status'),
        ),
    ]
