# Generated by Django 6.0.2 on 2026-03-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0010_status_departamento_status_empresa_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterModelTable(
            name='status',
            table='status',
        ),
    ]
