# Generated by Django 6.0.2 on 2026-03-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0011_alter_status_options_alter_status_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneda',
            name='status',
        ),
        migrations.RemoveField(
            model_name='satclaveunidad',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='satusocfdi',
            name='status',
        ),
        migrations.RemoveField(
            model_name='impuesto',
            name='status',
        ),
        migrations.RemoveField(
            model_name='unidadmedida',
            name='status',
        ),
        migrations.RemoveField(
            model_name='seriefolio',
            name='status',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='status',
        ),
        migrations.RemoveField(
            model_name='satclaveprodserv',
            name='status',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='status',
        ),
        migrations.RemoveField(
            model_name='satmetodopago',
            name='status',
        ),
        migrations.RemoveField(
            model_name='satregimenfiscal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='satformapago',
            name='status',
        ),
        migrations.AlterField(
            model_name='departamento',
            name='estatus',
            field=models.CharField(choices=[('active', 'Activo'), ('deleted', 'Eliminado'), ('archived', 'Archivado')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estatus',
            field=models.CharField(choices=[('active', 'Activo'), ('deleted', 'Eliminado'), ('archived', 'Archivado')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='estatus',
            field=models.CharField(choices=[('active', 'Activo'), ('deleted', 'Eliminado'), ('archived', 'Archivado')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='estatus',
            field=models.CharField(choices=[('active', 'Activo'), ('deleted', 'Eliminado'), ('archived', 'Archivado')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='satclaveprodserv',
            name='estatus',
            field=models.CharField(choices=[('active', 'Activo'), ('deleted', 'Eliminado'), ('archived', 'Archivado')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='satclaveunidad',
            name='estatus',
            field=models.CharField(choices=[('active', 'Activo'), ('deleted', 'Eliminado'), ('archived', 'Archivado')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='satformapago',
            name='estatus',
            field=models.CharField(choices=[('active', 'Activo'), ('deleted', 'Eliminado'), ('archived', 'Archivado')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='satmetodopago',
            name='estatus',
            field=models.CharField(choices=[('active', 'Activo'), ('deleted', 'Eliminado'), ('archived', 'Archivado')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='satregimenfiscal',
            name='estatus',
            field=models.CharField(choices=[('active', 'Activo'), ('deleted', 'Eliminado'), ('archived', 'Archivado')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='satusocfdi',
            name='estatus',
            field=models.CharField(choices=[('active', 'Activo'), ('deleted', 'Eliminado'), ('archived', 'Archivado')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='seriefolio',
            name='estatus',
            field=models.CharField(choices=[('active', 'Activo'), ('deleted', 'Eliminado'), ('archived', 'Archivado')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='estatus',
            field=models.CharField(choices=[('active', 'Activo'), ('deleted', 'Eliminado'), ('archived', 'Archivado')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='estatus',
            field=models.CharField(choices=[('active', 'Activo'), ('deleted', 'Eliminado'), ('archived', 'Archivado')], default='active', max_length=10),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
