# Generated by Django 6.0.2 on 2026-03-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0012_remove_moneda_status_remove_satclaveunidad_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresasatconfig',
            name='estatus',
            field=models.CharField(choices=[('active', 'Activo'), ('deleted', 'Eliminado'), ('archived', 'Archivado')], default='active', max_length=10),
        ),
    ]
