# Generated by Django 6.0.2 on 2026-02-27 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0003_color_talla_categoriaproducto_activo_and_more'),
        ('nucleo', '0009_seriefolio_incluir_anio_seriefolio_reiniciar_anual_and_more'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Oportunidad',
                'verbose_name_plural': 'Oportunidades',
                'db_table': 'oportunidades',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='terceros.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='nucleo.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='nucleo.moneda')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='nucleo.sucursal')),
                ('oportunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='ventas.oportunidad')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.SmallIntegerField(choices=[(1, 'Borrador'), (2, 'Por Autorizar'), (3, 'Autorizado'), (4, 'En Proceso'), (5, 'Cerrado')], default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='terceros.cliente')),
                ('cotizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='ventas.cotizacion')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='nucleo.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='nucleo.moneda')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='nucleo.sucursal')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='ventas.pedido')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'entregas',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='ventas.entrega')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='ventas.pedido')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'db_table': 'devoluciones',
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Pedido Detalle',
                'verbose_name_plural': 'Pedidos Detalle',
                'db_table': 'pedido_detalle',
            },
        ),
        migrations.CreateModel(
            name='EntregaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.entrega')),
                ('pedido_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='ventas.pedidodetalle')),
            ],
            options={
                'verbose_name': 'Entrega Detalle',
                'verbose_name_plural': 'Entregas Detalles',
                'db_table': 'entrega_detalle',
            },
        ),
        migrations.CreateModel(
            name='DevolucionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.devolucion')),
                ('entrega_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='ventas.entregadetalle')),
                ('pedido_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='ventas.pedidodetalle')),
            ],
            options={
                'verbose_name': 'Devolución Detalle',
                'verbose_name_plural': 'Devoluciones Detalle',
                'db_table': 'devolucion_detalle',
            },
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospectos', to='nucleo.empresa')),
            ],
            options={
                'verbose_name': 'Prospecto',
                'verbose_name_plural': 'Prospectos',
                'db_table': 'prospectos',
            },
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='prospecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='ventas.prospecto'),
        ),
    ]
