# Generated by Django 6.0.2 on 2026-03-05 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_tipoproducto_codigo'),
        ('nucleo', '0009_seriefolio_incluir_anio_seriefolio_reiniciar_anual_and_more'),
        ('terceros', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion', to='terceros.cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizacion', to='nucleo.empresa'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion', to='nucleo.moneda'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='oportunidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion', to='ventas.oportunidad'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizacion', to='nucleo.sucursal'),
        ),
        migrations.CreateModel(
            name='CotizacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciondetalle', to='ventas.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciondetalle', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Cotización Detalle',
                'verbose_name_plural': 'Cotizaciones Detalle',
                'db_table': 'cotizacion_detalle',
            },
        ),
    ]
