# Generated by Django 6.0.2 on 2026-03-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_cotizacion_cliente_alter_cotizacion_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.SmallIntegerField(choices=[(1, 'Stock'), (2, 'Fabricacion'), (3, 'Muestra'), (4, 'Mixto')], default=1),
        ),
    ]
