# Generated by Django 5.2 on 2026-03-20 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_pedido_activo_pedido_amazon_pedido_anticipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='ventas.cotizacion'),
        ),
    ]
