# Generated by Django 5.2 on 2026-03-23 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_producto_precio_base'),
        ('ventas', '0007_pedido_created_at_pedido_fecha_confirmacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodetalle',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='subtotal_linea',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedidodetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='catalogo.producto'),
        ),
        migrations.CreateModel(
            name='PedidoDetalleTalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal_talla', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pedido_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tallas', to='ventas.pedidodetalle')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedido_detalles_talla', to='catalogo.talla')),
            ],
            options={
                'verbose_name': 'Pedido Detalle Talla',
                'verbose_name_plural': 'Pedidos Detalle Tallas',
                'db_table': 'pedido_detalle_talla',
            },
        ),
    ]
