# Generated by Django 5.2 on 2026-03-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_pedidodetalle_costo_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodetalletalla',
            name='lleva_bordado',
            field=models.BooleanField(default=False),
        ),
    ]
