# Generated by Django 5.2 on 2026-03-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_pedido_folio_pedido_folio_anio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='folio_anio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='folio_consecutivo',
        ),
    ]
