# Generated by Django 5.2 on 2026-03-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('terceros', '0009_direccioncliente_celular_envio_and_more'),
        ('ventas', '0011_remove_pedido_folio_remove_pedido_folio_anio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='folio',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='folio_consecutivo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(fields=('serie_folio', 'folio'), name='uq_pedido_seriefolio_folio'),
        ),
    ]
