# Generated by Django 5.2 on 2026-03-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_pedido_folio_pedido_folio_consecutivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodetalletalla',
            name='bordado_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
