# Generated by Django 5.2 on 2026-03-24 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('ventas', '0013_pedidodetalletalla_bordado_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_ciudad',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_colonia',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_direccion_fiscal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_estado',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_giro_empresarial',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_razon_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_regimen_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='nucleo.satregimenfiscal'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
