# Generated by Django 5.2 on 2026-03-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_cotizacion_cliente_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente_ciudad',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente_codigo_postal',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente_colonia',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente_direccion_fiscal',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente_estado',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente_giro_empresarial',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente_nombre',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente_razon_social',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente_regimen_fiscal',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente_rfc',
        ),
    ]
