# Generated by Django 5.2 on 2026-03-25 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_producto_precio_base'),
        ('ventas', '0016_pedido_cliente_ciudad_pedido_cliente_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='aprobado_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='autorizada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cambios_solicitados_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='estatus',
            field=models.SmallIntegerField(choices=[(1, 'Borrador'), (2, 'Por Autorizar'), (3, 'Autorizada'), (4, 'Rechazada'), (5, 'Cambios Por Autorizar')], default=2),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='subtotal_linea',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='CotizacionDetalleTalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal_talla', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lleva_bordado', models.BooleanField(default=False)),
                ('bordado_config', models.JSONField(blank=True, null=True)),
                ('cotizacion_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tallas', to='ventas.cotizaciondetalle')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizacion_detalles_talla', to='catalogo.talla')),
            ],
            options={
                'verbose_name': 'Cotización Detalle Talla',
                'verbose_name_plural': 'Cotizaciones Detalle Tallas',
                'db_table': 'cotizacion_detalle_talla',
            },
        ),
    ]
