# Generated by Django 5.2 on 2026-03-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_cotizacion_aprobado_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estatus',
            field=models.SmallIntegerField(choices=[(1, 'Borrador'), (2, 'Por Autorizar'), (3, 'Autorizada'), (4, 'Rechazada'), (5, 'Cambios Por Autorizar')], db_index=True, default=2),
        ),
    ]
