# Generated by Django 5.2 on 2026-03-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0019_cotizacion_vendedor_alter_cotizacion_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='oc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
