# Generated by Django 5.2 on 2026-03-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0021_cotizacion_celular_envio_cotizacion_ciudad_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estatus',
            field=models.SmallIntegerField(choices=[(1, 'BORRADOR'), (2, 'POR AUTORIZAR'), (3, 'AUTORIZADA'), (4, 'RECHAZADA'), (5, 'CAMBIOS POR AUTORIZAR')], db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='forma_pago',
            field=models.CharField(choices=[('01', '01 - EFECTIVO'), ('03', '03 - TRANSFERENCIA'), ('04', '04 - TARJETA')], max_length=5),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='metodo_pago',
            field=models.CharField(choices=[('PUE', 'PUE - PAGO EN UNA SOLA EXIBICIÓN'), ('PPD', 'PPD - PAGO EN PARCIALIDADES'), ('NA', 'N/A')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='uso_cfdi',
            field=models.CharField(choices=[('G03', 'G03 - GASTOS EN GENERAL (OTROS) (OTROS)'), ('G01', 'G01 - ADQUISICIÓN DE MERCANCIAS'), ('I01', 'I01 - CONSTRUCCIONES')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estatus',
            field=models.SmallIntegerField(choices=[(1, 'BORRADOR'), (2, 'POR AUTORIZAR'), (3, 'AUTORIZADA'), (4, 'EN PROCESO'), (5, 'CANCELADO')], default=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pago',
            field=models.CharField(choices=[('01', '01 - EFECTIVO'), ('03', '03 - TRANSFERENCIA'), ('04', '04 - TARJETA')], max_length=5),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('PUE', 'PUE - PAGO EN UNA SOLA EXIBICIÓN'), ('PPD', 'PPD - PAGO EN PARCIALIDADES'), ('NA', 'N/A')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.SmallIntegerField(choices=[(1, 'STOCK'), (2, 'FABRICACION'), (3, 'MUESTRAS'), (4, 'MIXTOs')], default=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='uso_cfdi',
            field=models.CharField(choices=[('G03', 'G03 - GASTOS EN GENERAL (OTROS) (OTROS)'), ('G01', 'G01 - ADQUISICIÓN DE MERCANCIAS'), ('I01', 'I01 - CONSTRUCCIONES')], max_length=10),
        ),
    ]
