# Generated by Django 5.2 on 2026-03-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0022_alter_cotizacion_estatus_alter_cotizacion_forma_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='reflejante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='serigrafia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='reflejante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='serigrafia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
