# Generated by Django 5.2 on 2026-04-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0023_cotizacion_reflejante_cotizacion_serigrafia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.SmallIntegerField(choices=[(1, 'PEDIDO DE VENTA'), (2, 'MUESTRA'), (3, 'PEDIDO DE ERROR')], default=1),
        ),
    ]
