# Generated by Django 5.2 on 2026-04-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0024_alter_pedido_tipo_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciondetalletalla',
            name='lleva_serigrafia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotizaciondetalletalla',
            name='serigrafia_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidodetalletalla',
            name='lleva_serigrafia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidodetalletalla',
            name='serigrafia_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
