# Generated by Django 5.2 on 2026-04-09 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0025_cotizaciondetalletalla_lleva_serigrafia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='precio_lista',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='precio_lista',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='CotizacionServicioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('visible_en_factura', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_extras', to='ventas.cotizacion')),
            ],
            options={
                'verbose_name': 'Cotización Servicio Extra',
                'verbose_name_plural': 'Cotizaciones Servicios Extras',
                'db_table': 'cotizacion_servicios_extras',
            },
        ),
        migrations.CreateModel(
            name='PedidoServicioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('visible_en_factura', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_extras', to='ventas.pedido')),
            ],
            options={
                'verbose_name': 'Pedido Servicio Extra',
                'verbose_name_plural': 'Pedidos Servicios Extras',
                'db_table': 'pedido_servicios_extras',
            },
        ),
    ]
