# Generated by Django 5.2 on 2026-04-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0026_cotizaciondetalle_precio_lista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizaciondetalletalla',
            name='serigrafia_config',
        ),
        migrations.RemoveField(
            model_name='pedidodetalletalla',
            name='serigrafia_config',
        ),
        migrations.AddField(
            model_name='cotizaciondetalletalla',
            name='dtf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotizaciondetalletalla',
            name='revelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotizaciondetalletalla',
            name='sublimado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidodetalletalla',
            name='dtf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidodetalletalla',
            name='revelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidodetalletalla',
            name='sublimado',
            field=models.BooleanField(default=False),
        ),
    ]
