# Generated by Django 5.2 on 2026-04-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0027_remove_cotizaciondetalletalla_serigrafia_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizaciondetalletalla',
            name='dtf',
        ),
        migrations.RemoveField(
            model_name='cotizaciondetalletalla',
            name='revelado',
        ),
        migrations.RemoveField(
            model_name='cotizaciondetalletalla',
            name='sublimado',
        ),
        migrations.RemoveField(
            model_name='pedidodetalletalla',
            name='dtf',
        ),
        migrations.RemoveField(
            model_name='pedidodetalletalla',
            name='revelado',
        ),
        migrations.RemoveField(
            model_name='pedidodetalletalla',
            name='sublimado',
        ),
        migrations.AddField(
            model_name='cotizaciondetalletalla',
            name='serigrafia_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidodetalletalla',
            name='serigrafia_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
