# Generated by Django 6.0.4 on 2026-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0028_remove_cotizaciondetalletalla_dtf_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cotizaciondetalletalla",
            old_name="lleva_serigrafia",
            new_name="lleva_reflejante",
        ),
        migrations.RenameField(
            model_name="cotizaciondetalletalla",
            old_name="serigrafia_config",
            new_name="reflejante_config",
        ),
        migrations.RenameField(
            model_name="pedidodetalletalla",
            old_name="lleva_serigrafia",
            new_name="lleva_reflejante",
        ),
        migrations.RenameField(
            model_name="pedidodetalletalla",
            old_name="serigrafia_config",
            new_name="reflejante_config",
        ),
        migrations.AddField(
            model_name="cotizaciondetalletalla",
            name="lleva_corte_manga",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cotizaciondetalletalla",
            name="corte_manga_config",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cotizaciondetalletalla",
            name="lleva_cambio_talla",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cotizaciondetalletalla",
            name="cambio_talla_config",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedidodetalletalla",
            name="lleva_corte_manga",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pedidodetalletalla",
            name="corte_manga_config",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedidodetalletalla",
            name="lleva_cambio_talla",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pedidodetalletalla",
            name="cambio_talla_config",
            field=models.JSONField(blank=True, null=True),
        ),
    ]

