# Generated by Django 6.0.4 on 2026-04-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0030_alter_cotizacion_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estatus',
            field=models.SmallIntegerField(choices=[(1, 'BORRADOR'), (2, 'ENVIAR A AUTORIZACION'), (3, 'EN REVISION'), (4, 'RECHAZADA'), (5, 'CAMBIOS SOLICITADOS'), (6, 'AUTORIZADA')], db_index=True, default=2),
        ),
    ]
