# Generated by Django 5.2 on 2026-05-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_productovariante_nombre'),
        ('terceros', '0011_alter_cliente_ciudad_alter_cliente_codigo_postal_and_more'),
        ('ventas', '0031_alter_cotizacion_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizacion_detalles', to='catalogo.color'),
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='direccion_envio_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizacion_detalles', to='terceros.direccioncliente'),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_detalles', to='catalogo.color'),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='direccion_envio_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_detalles', to='terceros.direccioncliente'),
        ),
    ]
