# Generated by Django 5.2 on 2026-05-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0032_cotizaciondetalle_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciondetalletalla',
            name='sku',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
