# Generated by Django 5.2 on 2026-05-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0034_cotizacionservicioextra_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estatus',
            field=models.SmallIntegerField(choices=[(1, 'BORRADOR'), (2, 'EN REVISION'), (3, 'AUTORIZADA'), (4, 'RECHAZADA'), (5, 'CAMBIOS SOLICITADOS')], db_index=True, default=1),
        ),
    ]
