# Generated by Django 6.0.5 on 2026-05-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0035_alter_cotizacion_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciondetalletalla',
            name='requiere_produccion',
            field=models.BooleanField(default=False),
        ),
    ]
