# Generated by Django 6.0.4 on 2026-05-25 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_productovariante_nombre'),
        ('ventas', '0036_cotizaciondetalletalla_requiere_produccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciondetalletalla',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_tallas', to='catalogo.productovariante'),
        ),
        migrations.AddField(
            model_name='pedidodetalletalla',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_tallas', to='catalogo.productovariante'),
        ),
    ]
