# Generated by Django 5.2 on 2026-05-26 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('terceros', '0011_alter_cliente_ciudad_alter_cliente_codigo_postal_and_more'),
        ('ventas', '0037_cotizaciondetalletalla_variante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion', to='terceros.cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='correo_facturas',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizacion', to='nucleo.empresa'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('01', '01 - EFECTIVO'), ('03', '03 - TRANSFERENCIA'), ('04', '04 - TARJETA')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('PUE', 'PUE - PAGO EN UNA SOLA EXIBICIÓN'), ('PPD', 'PPD - PAGO EN PARCIALIDADES'), ('NA', 'N/A')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion', to='nucleo.moneda'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='persona_pagos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizacion', to='nucleo.sucursal'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='telefono_pagos',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='uso_cfdi',
            field=models.CharField(blank=True, choices=[('G03', 'G03 - GASTOS EN GENERAL (OTROS) (OTROS)'), ('G01', 'G01 - ADQUISICIÓN DE MERCANCIAS'), ('I01', 'I01 - CONSTRUCCIONES')], max_length=10, null=True),
        ),
    ]
