# Generated by Django 6.0.4 on 2026-07-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0039_historicalcotizacion_historicalpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_pedido',
            field=models.SmallIntegerField(choices=[(1, 'PEDIDO DE VENTA'), (2, 'MUESTRA'), (3, 'PEDIDO DE ERROR')], default=1),
        ),
        migrations.AddField(
            model_name='historicalcotizacion',
            name='tipo_pedido',
            field=models.SmallIntegerField(choices=[(1, 'PEDIDO DE VENTA'), (2, 'MUESTRA'), (3, 'PEDIDO DE ERROR')], default=1),
        ),
    ]
