# Generated by Django 6.0.6 on 2026-08-28 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_historicalcategoriaproducto_historicalproducto_and_more'),
        ('ventas', '0040_cotizacion_tipo_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='producto_nombre_externo',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='producto_nombre_externo',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciondetalle', to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='pedidodetalle',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='catalogo.producto'),
        ),
    ]
