# Generated by Django 6.0.7 on 2026-08-24 22:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('terceros', '0015_alter_historicalproveedor_fax_alter_proveedor_fax'),
        ('ventas', '0040_cotizacion_tipo_pedido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devolucion',
            name='estatus',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='motivo',
            field=models.CharField(choices=[('PRODUCTO_DANADO', 'Producto dañado'), ('PRODUCTO_INCORRECTO', 'Producto incorrecto'), ('CANTIDAD_INCORRECTA', 'Cantidad incorrecta'), ('RECHAZO_CLIENTE', 'Rechazo del cliente'), ('OTRO', 'Otro')], default='Otro', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devolucion',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='devoluciondetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrega',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrega',
            name='estatus',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROGRAMADA', 'Programada'), ('EN_TRANSITO', 'En tránsito'), ('ENTREGADA', 'Entregada'), ('PARCIAL', 'Parcial'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='entrega',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='folio',
            field=models.CharField(default='defaultfolio', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrega',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='recibido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrega',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entregadetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='nucleo.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='estatus',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('GANADA', 'Ganada'), ('PERDIDA', 'Perdida'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=20),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='etapa',
            field=models.CharField(choices=[('CALIFICACION', 'Calificación'), ('PROPUESTA', 'Propuesta'), ('NEGOCIACION', 'Negociación'), ('CIERRE', 'Cierre')], default='CALIFICACION', max_length=20),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='fecha_estimada_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='monto_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='nombre',
            field=models.CharField(default='defaultname', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='cargo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='terceros.cliente'),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='convertido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospecto',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='fecha_conversion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='nombre',
            field=models.CharField(default='defaulname', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospecto',
            name='sitio_web',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='prospectos', to='nucleo.sucursal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospecto',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ActividadCrm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades_crm', to='terceros.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_crm', to='nucleo.empresa')),
                ('oportunidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_crm', to='ventas.oportunidad')),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_crm', to='ventas.prospecto')),
            ],
        ),
        migrations.CreateModel(
            name='Backorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backorders', to='nucleo.empresa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backorders', to='ventas.pedido')),
            ],
            options={
                'verbose_name': 'Backorder',
                'verbose_name_plural': 'Backorders',
                'db_table': 'backorders',
            },
        ),
        migrations.CreateModel(
            name='BackorderDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backorder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backorder_detalles', to='ventas.backorder')),
                ('pedido_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backorder_detalles', to='ventas.pedidodetalle')),
            ],
            options={
                'verbose_name': 'Backorder detalle',
                'verbose_name_plural': 'Backorder detalles',
                'db_table': 'backorder_detalle',
            },
        ),
    ]
