# Generated by Django 6.0.7 on 2026-08-25 15:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('ventas', '0041_devolucion_created_at_devolucion_estatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backorder',
            name='estatus',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='backorder',
            name='fecha_estimada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backorder',
            name='folio',
            field=models.CharField(default='defaultfolio', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backorder',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='backorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='backorderdetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devolucion',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='nucleo.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrega',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='nucleo.empresa'),
            preserve_default=False,
        ),
    ]
