# Generated by Django 6.0.5 on 2026-08-31 13:56

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('terceros', '0016_cliente_clientes_nombre_trgm_and_more'),
        ('ventas', '0041_allow_external_products'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pedido',
            index=django.contrib.postgres.indexes.GinIndex(fields=['cliente_nombre'], name='pedidos_cliente_nombre_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=django.contrib.postgres.indexes.GinIndex(fields=['cliente_razon_social'], name='pedidos_cliente_rsocial_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
