# Generated by Django 6.0.4 on 2026-09-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0042_pedido_pedidos_cliente_nombre_trgm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoservicioextra',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='cantidad'),
        ),
    ]
