# Generated by Django 6.0.4 on 2026-09-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0043_pedidoservicioextra_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedido',
            name='cantidad_embarque',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpedido',
            name='cantidad_surtir_apartados',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpedido',
            name='cantidad_surtir_bordado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpedido',
            name='fecha_embarque',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpedido',
            name='fecha_surtir_apartados',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpedido',
            name='fecha_surtir_bordado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cantidad_embarque',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cantidad_surtir_apartados',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cantidad_surtir_bordado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_embarque',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_surtir_apartados',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_surtir_bordado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
