# Generated by Django 6.0.4 on 2026-09-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0044_historicalpedido_cantidad_embarque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('A', 'A - 2 a 5 días'), ('B', 'B - 5 a 8 días'), ('C', 'C - 5 a 15 días'), ('D', 'D - 4 a 6 semanas'), ('E', 'E - 6 a 8 semanas'), ('F', 'F - 8 a 10 semanas'), ('X', 'X - Solo para facturar')], help_text='Clasificación de tiempo de entrega', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalcotizacion',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('A', 'A - 2 a 5 días'), ('B', 'B - 5 a 8 días'), ('C', 'C - 5 a 15 días'), ('D', 'D - 4 a 6 semanas'), ('E', 'E - 6 a 8 semanas'), ('F', 'F - 8 a 10 semanas'), ('X', 'X - Solo para facturar')], help_text='Clasificación de tiempo de entrega', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalpedido',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('A', 'A - 2 a 5 días'), ('B', 'B - 5 a 8 días'), ('C', 'C - 5 a 15 días'), ('D', 'D - 4 a 6 semanas'), ('E', 'E - 6 a 8 semanas'), ('F', 'F - 8 a 10 semanas'), ('X', 'X - Solo para facturar')], db_index=True, help_text='Clasificación de tiempo de entrega: A=2-5d, B=5-8d, C=5-15d, D=4-6sem, E=6-8sem, F=8-10sem, X=Solo facturar', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('A', 'A - 2 a 5 días'), ('B', 'B - 5 a 8 días'), ('C', 'C - 5 a 15 días'), ('D', 'D - 4 a 6 semanas'), ('E', 'E - 6 a 8 semanas'), ('F', 'F - 8 a 10 semanas'), ('X', 'X - Solo para facturar')], db_index=True, help_text='Clasificación de tiempo de entrega: A=2-5d, B=5-8d, C=5-15d, D=4-6sem, E=6-8sem, F=8-10sem, X=Solo facturar', max_length=1, null=True),
        ),
    ]
