# Generated by Django 6.0.4 on 2026-09-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0045_cotizacion_clasificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpedido',
            name='cantidad_embarque',
        ),
        migrations.RemoveField(
            model_name='historicalpedido',
            name='cantidad_surtir_apartados',
        ),
        migrations.RemoveField(
            model_name='historicalpedido',
            name='cantidad_surtir_bordado',
        ),
        migrations.RemoveField(
            model_name='historicalpedido',
            name='fecha_embarque',
        ),
        migrations.RemoveField(
            model_name='historicalpedido',
            name='fecha_surtir_apartados',
        ),
        migrations.RemoveField(
            model_name='historicalpedido',
            name='fecha_surtir_bordado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad_embarque',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad_surtir_apartados',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad_surtir_bordado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_embarque',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_surtir_apartados',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_surtir_bordado',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='programacion_conf',
            field=models.JSONField(blank=True, default=dict, help_text='Programación de maquila con múltiples fechas y cantidades de entrega', null=True),
        ),
        migrations.AddField(
            model_name='historicalcotizacion',
            name='programacion_conf',
            field=models.JSONField(blank=True, default=dict, help_text='Programación de maquila con múltiples fechas y cantidades de entrega', null=True),
        ),
        migrations.AddField(
            model_name='historicalpedido',
            name='programacion_conf',
            field=models.JSONField(blank=True, default=dict, help_text='Programación de maquila con múltiples fechas y cantidades de entrega', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='programacion_conf',
            field=models.JSONField(blank=True, default=dict, help_text='Programación de maquila con múltiples fechas y cantidades de entrega', null=True),
        ),
    ]
