# Generated by Django 6.0.6 on 2026-09-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0046_remove_historicalpedido_cantidad_embarque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodetalletalla',
            name='requiere_produccion',
            field=models.BooleanField(default=False),
        ),
    ]
