# Generated by Django 6.0.5 on 2026-10-02 15:11

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations, models

from nucleo.migration_operations import AddIndexSoloPostgres


# Sustituye los GIN trigram v1 sobre la columna cruda —que ningún lookup del ORM
# puede usar: Django emite ``UPPER("col"::text) LIKE UPPER(%s)``— por índices de
# expresión sobre ``UPPER(col)``. Ver ``AddIndexSoloPostgres`` para el porqué de
# la operación propia.


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('terceros', '0017_indices_busqueda_upper'),
        ('ventas', '0047_pedidodetalletalla_requiere_produccion'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedidos_cliente_nombre_trgm',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedidos_cliente_rsocial_trgm',
        ),
        AddIndexSoloPostgres(
            model_name='pedido',
            index=models.Index(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('folio'), name='text_pattern_ops'), name='pedidos_folio_upper_like'),
        ),
        AddIndexSoloPostgres(
            model_name='pedido',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('cliente_nombre'), name='gin_trgm_ops'), name='pedidos_cli_nom_upper_trgm'),
        ),
        AddIndexSoloPostgres(
            model_name='pedido',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('cliente_razon_social'), name='gin_trgm_ops'), name='pedidos_cli_rs_upper_trgm'),
        ),
    ]
