# Generated by Django 6.0.5 on 2026-10-05 13:25

import django.contrib.postgres.indexes
import django.db.models.functions.text
import nucleo.indices
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0047_pedidodetalletalla_requiere_produccion'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedidos_cliente_nombre_trgm',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedidos_cliente_rsocial_trgm',
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=nucleo.indices.IndexSoloPostgres(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('folio'), name='text_pattern_ops'), name='pedidos_folio_upper_like'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=nucleo.indices.GinIndexSoloPostgres(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('cliente_nombre'), name='gin_trgm_ops'), name='pedidos_cli_nom_upper_trgm'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=nucleo.indices.GinIndexSoloPostgres(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('cliente_razon_social'), name='gin_trgm_ops'), name='pedidos_cli_rs_upper_trgm'),
        ),
    ]
