# Generated by Django 6.0.7 on 2026-10-09 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0026_historicalvarianteproductoproduccion_activo_and_more'),
        ('ventas', '0048_indices_busqueda_upper'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='categoria_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizacion_detalles', to='catalogo.categoriaproducto'),
        ),
    ]
