# Generated by Django 6.0.7 on 2026-10-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0049_cotizaciondetalle_categoria_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciondetalletalla',
            name='sku_muestra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidodetalletalla',
            name='sku_muestra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
