# Generated by Django 6.0.6 on 2026-08-13 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, help_text='Clave corta del area', max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='nucleo.departamento')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='hr.empleado')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'areas',
            },
        ),
    ]
