# Generated by Django 6.0.6 on 2026-08-13 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puestos', to='hr.area'),
        ),
    ]
