# Generated by Django 6.0.6 on 2026-09-01 16:05

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_puesto_area'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productividaddetalle',
            options={'verbose_name': 'Productividad Detalle', 'verbose_name_plural': 'Productividad Detalle'},
        ),
        migrations.AddField(
            model_name='asistencia',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='horas_extra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='horas_normales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='minutos_retardo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='minutos_tolerancia',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='constancia_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='estado',
            field=models.CharField(choices=[('inscrito', 'Inscrito'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='inscrito', max_length=20),
        ),
        migrations.AddField(
            model_name='contrato',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='prestaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlhoras',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='calle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='clabe',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='email_emergencia',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='enfermedades_cronicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('soltero', 'Soltero(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viudo', 'Viudo(a)'), ('union_libre', 'Unión libre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='foto_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='infonavit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='moneda_pago',
            field=models.CharField(blank=True, default='MXN', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nacionalidad',
            field=models.CharField(blank=True, default='Mexicana', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre_emergencia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nss',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='numero_exterior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='numero_interior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='parentesco_emergencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_sangre',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados_turno', to='hr.turno'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='periodo',
            field=models.CharField(choices=[('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='anual', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tipo',
            field=models.CharField(choices=[('desempeno', 'Desempeño'), ('competencias', 'Competencias'), ('objetivo', 'Por objetivos')], default='desempeno', max_length=20),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='acciones_tomadas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='fecha_reporte',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='gravedad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='baja', max_length=20),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='reportado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nomina',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nominas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nomina',
            name='dias_pagados',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='nomina',
            name='fecha_generacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='nomina',
            name='horas_extra_pagadas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='nomina',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomina',
            name='salario_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nominadetalle',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='nominadetalle',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nominadetalle',
            name='unidad',
            field=models.CharField(blank=True, default='MXN', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='permisoausencia',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisos_autorizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permisoausencia',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permisoausencia',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permisoausencia',
            name='fecha_solicitud',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='permisoausencia',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permisoausencia',
            name='rechazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisos_rechazados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permisoausencia',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisos_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productividad',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productividad_creada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productividad',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='turno',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='horas_base_diarias',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='turno',
            name='tolerancia_retardo_minutos',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacaciones_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='dias_disponibles_al_momento',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='fecha_solicitud',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='rechazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacaciones_rechazadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacaciones_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_empleado',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('empleado', 'fecha'), name='unique_asistencia_empleado_fecha'),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_empleado'), name='unique_numero_empleado_empresa'),
        ),
    ]
