# Generated by Django 6.0.5 on 2026-09-18 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_normaliza_curp_rfc_nss_vacios_a_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('estado', 'activo')), fields=('empleado',), name='uq_contrato_vigente_por_empleado', violation_error_message='Este empleado ya tiene un contrato activo.'),
        ),
    ]
