# Generated by Django 6.0.5 on 2026-10-05 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_contrato_uq_contrato_vigente_por_empleado'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nomina',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'cancelada'), _negated=True), fields=('empleado', 'periodo_inicio', 'periodo_fin'), name='uq_nomina_empleado_periodo_vigente', violation_error_message='Este empleado ya tiene una nómina vigente para este periodo.'),
        ),
    ]
