import pandas as pd

diccionario = {
    #PRENDAS SUPERIORES
    "CAMISA": "PRENDAS SUPERIORES",
    "BLUSA": "PRENDAS SUPERIORES",
    "BLUSON": "PRENDAS SUPERIORES",
    "CAMISETA": "PRENDAS SUPERIORES",
    "PLAYERA": "PRENDAS SUPERIORES",
    "CAMISOLA": "PRENDAS SUPERIORES",
    "GUAYABERA": "PRENDAS SUPERIORES",
    "FILIPINA": "PRENDAS SUPERIORES",
    "CASACA": "PRENDAS SUPERIORES",
    "SACO": "PRENDAS SUPERIORES",
    "POLO": "PRENDAS SUPERIORES",

    #PRENDAS INFERIORES
    "PANTALON": "PRENDAS INFERIORES",
    "PANTALÓN": "PRENDAS INFERIORES",
    "BERMUDA": "PRENDAS INFERIORES",
    "SHORT": "PRENDAS INFERIORES",
    "CALZON": "PRENDAS INFERIORES",
    "FAJA": "PRENDAS INFERIORES",
    "VESTIDO": "PRENDAS INFERIORES",

    #PROTECCION CLIMA
    "CHALECO": "PROTECCION CLIMA",
    "CHAMARRA": "PROTECCION CLIMA",
    "Chamarra": "PROTECCION CLIMA",
    "CHALECO_DE_SEGURIDAD": "PROTECCION CLIMA",
    "CHALECO_INDUSTRIAL": "PROTECCION CLIMA",
    "IMPERMEABLE": "PROTECCION CLIMA",
    "ROMPEVIENTOS": "PROTECCION CLIMA",
    "ROMPEVIENDOS": "PROTECCION CLIMA",
    "ROMPEVIENTO": "PROTECCION CLIMA",
    "SUDADERA": "PROTECCION CLIMA",
    "SUETER": "PROTECCION CLIMA",
    "CAPA": "PROTECCION CLIMA",
    "CHAQUETA": "PROTECCION CLIMA",

    #CALZADO
    "ZAPATOS": "CALZADO",
    "ZAPATO": "CALZADO",
    "TENIS": "CALZADO",
    "BOTAS": "CALZADO",
    "BOTA": "CALZADO",

    #ACCESORIOS
    "GORRA": "ACCESORIOS",
    "GORRO": "ACCESORIOS",
    "GORRITO": "ACCESORIOS",
    "SOMBRERO": "ACCESORIOS",
    "CINTURON": "ACCESORIOS",
    "CINTURONES": "ACCESORIOS",
    "CINTURÓN": "ACCESORIOS",
    "CORBATAS": "ACCESORIOS",
    "CORBATA": "ACCESORIOS",
    "CORBATINES": "ACCESORIOS",
    "MOÑOS": "ACCESORIOS",
    "MOÑO": "ACCESORIOS",
    "PAÑOLETA": "ACCESORIOS",
    "PAÑOLETAS": "ACCESORIOS",
    "PANOLETAS": "ACCESORIOS",
    "PASAMONTAÑAS": "ACCESORIOS",
    "BANDA": "ACCESORIOS",
    "MASCADAS": "ACCESORIOS",
    "BOLSA": "ACCESORIOS",
    "PORTA HERRAMIENTAS": "ACCESORIOS",
    "PORTAHERRAMIENTAS": "ACCESORIOS",

    #INDUSTRIAL
    "BATA": "INDUSTRIAL",
    "OVEROL": "INDUSTRIAL",
    "MANDIL": "INDUSTRIAL",
    "MANDILES": "INDUSTRIAL",
    "COFIA": "INDUSTRIAL",
    "CUBREBOCAS": "INDUSTRIAL",
    "CUBRE BOCA": "INDUSTRIAL",
    "CUBRECABECERA": "INDUSTRIAL",
    "MANGAS": "INDUSTRIAL",
    "BABERO": "INDUSTRIAL",
    "CUELLERA": "INDUSTRIAL",

    #EQUIPO DE SEGURIDAD
    "CASCO": "EQUIPO DE SEGURIDAD",
    "GOGLES": "EQUIPO DE SEGURIDAD",
    "LENTES": "EQUIPO DE SEGURIDAD",
    "LENTE": "EQUIPO DE SEGURIDAD",
    "CARETAS": "EQUIPO DE SEGURIDAD",
    "CARETA": "EQUIPO DE SEGURIDAD",
    "GUANTES": "EQUIPO DE SEGURIDAD",
    "GUANTE": "EQUIPO DE SEGURIDAD",
    "OREJERAS": "EQUIPO DE SEGURIDAD",
    "TAPONES": "EQUIPO DE SEGURIDAD",
    "TAPON": "EQUIPO DE SEGURIDAD",
    "RODILLERAS": "EQUIPO DE SEGURIDAD",
    "ESCAFANDRA": "EQUIPO DE SEGURIDAD",
    "VISERA": "EQUIPO DE SEGURIDAD",
    "VISERAS": "EQUIPO DE SEGURIDAD",
    "SORDERAS": "EQUIPO DE SEGURIDAD",


    #INSUMOS
    "DESINFECTANTE": "INSUMOS",
    "TERMOMETRO": "INSUMOS",
    "TOALLAS": "INSUMOS",
    "TOALLA": "INSUMOS",
    "SERVILLETAS": "INSUMOS",
    "SERVILLETA": "INSUMOS",
    "TAPETE": "INSUMOS",
    "TORTILLEROS": "INSUMOS",

    #OTROS
    "COBIJA": "OTROS",
    "SEGURIDAD": "OTROS",
    "OTROS": "OTROS",
}

#Base de codigos
base_codigos = {
    "PRENDAS SUPERIORES": 1000,
    "PRENDAS INFERIORES": 2000,
    "PROTECCION CLIMA": 3000,
    "CALZADO": 4000,
    "ACCESORIOS": 5000,
    "INDUSTRIAL": 6000,
    "EQUIPO DE SEGURIDAD": 7000,
    "INSUMOS": 8000,
    "OTROS": 9000,
}

#Contadores dinamicos
contadores = base_codigos.copy()

#Funciones
def obtener_categoria(producto):
    primera = str(producto).split()[0]
    return diccionario.get(primera, "OTROS")

def asignar_codigo(categoria):
    codigo = contadores[categoria]
    contadores[categoria] += 1
    return codigo

#leer el excel
archivo = pd.read_excel('./doc/TODOS-LOS-PRODUCTOS.xlsx')
print(archivo.head())
print('-----------------')

#Proceso
archivo["CATEGORIA_PADRE"] = archivo["PRODUCTOS"].apply(obtener_categoria)
archivo["CODIGO_CALCULADO"] = archivo["CATEGORIA_PADRE"].apply(asignar_codigo)

#Mostrar resultados
print("---------- RESULTADO ----------")
print(archivo[["PRODUCTOS", "CATEGORIA", "CATEGORIA_PADRE", "CODIGO_CALCULADO", "SKU"]].head(30))

#crear archivo excel
archivo.to_excel('./doc/TODOS-LOS-PRODUCTOS-CON-CODIGOS.xlsx', index=False)