# Generated by Django 6.0.5 on 2026-06-08 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0013_productovariante_nombre'),
        ('inventarios', '0011_ajusteinventario_activo_and_more'),
        ('logistica', '0001_initial'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('ventas', '0038_alter_cotizacion_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Packing',
                'verbose_name_plural': 'Packings',
                'db_table': 'packing',
            },
        ),
        migrations.CreateModel(
            name='ConteoCiclico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteo_ciclico', to='inventarios.almacen')),
            ],
            options={
                'verbose_name': 'Conteo Ciclico',
                'verbose_name_plural': 'Conteos Cíclicos',
                'db_table': 'conteos_ciclico',
            },
        ),
        migrations.CreateModel(
            name='ConteoCiclicoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteo_ciclico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteo_ciclico_detalle', to='wms.conteociclico')),
                ('existencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteo_ciclico_detalle', to='inventarios.existencia')),
            ],
            options={
                'verbose_name': 'Conteo Ciclico Detalle',
                'verbose_name_plural': 'Conteos Cíclicos Detalles',
                'db_table': 'conteo_ciclico_detalle',
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='logistica.envio')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='wms.packing')),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'db_table': 'despachos',
            },
        ),
        migrations.CreateModel(
            name='PackingDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_detalle', to='wms.packing')),
            ],
            options={
                'verbose_name': 'Packing Detalle',
                'verbose_name_plural': 'Packing Detalles',
                'db_table': 'packing_detalle',
            },
        ),
        migrations.CreateModel(
            name='DespachoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despacho_detalle', to='wms.despacho')),
                ('packing_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despacho_detalle', to='wms.packingdetalle')),
            ],
            options={
                'verbose_name': 'Despacho Detalle',
                'verbose_name_plural': 'Despacho Detalles',
                'db_table': 'despacho_detalle',
            },
        ),
        migrations.CreateModel(
            name='Picking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickings', to='ventas.pedido')),
            ],
            options={
                'verbose_name': 'Picking',
                'verbose_name_plural': 'Pickings',
                'db_table': 'picking',
            },
        ),
        migrations.AddField(
            model_name='packing',
            name='picking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packings', to='wms.picking'),
        ),
        migrations.CreateModel(
            name='PickingDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picking_detalle', to='ventas.pedidodetalle')),
                ('picking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picking_detalle', to='wms.picking')),
            ],
            options={
                'verbose_name': 'Picking Detalle',
                'verbose_name_plural': 'Picking Detalles',
                'db_table': 'picking_detalle',
            },
        ),
        migrations.AddField(
            model_name='packingdetalle',
            name='picking_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_detalle', to='wms.pickingdetalle'),
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='nucleo.empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='nucleo.sucursal')),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'db_table': 'transferencias',
            },
        ),
        migrations.CreateModel(
            name='TransferenciaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_detalle', to='inventarios.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_detalle', to='catalogo.producto')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_detalle', to='inventarios.serie')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_detalle', to='wms.transferencia')),
                ('ubicacion_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_detalle_destino', to='inventarios.ubicacion')),
                ('ubicacion_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_detalle_origen', to='inventarios.ubicacion')),
            ],
            options={
                'verbose_name': 'Transferencia Detalle',
                'verbose_name_plural': 'Transferencias Detalles',
                'db_table': 'transferencia_detalle',
            },
        ),
    ]
