# Generated by Django 6.0.5 on 2026-07-09 17:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_historicalcategoriaproducto_historicalproducto_and_more'),
        ('inventarios', '0016_movimientoinventariodetalle_producto_variante'),
        ('wms', '0002_historicaltransferencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransferencia',
            name='almacen_destino',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventarios.almacen'),
        ),
        migrations.AddField(
            model_name='historicaltransferencia',
            name='almacen_origen',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventarios.almacen'),
        ),
        migrations.AddField(
            model_name='historicaltransferencia',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltransferencia',
            name='folio',
            field=models.CharField(default='default123', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltransferencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransferencia',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicaltransferencia',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='almacen_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='inventarios.almacen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferencia',
            name='almacen_origen',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origen', to='inventarios.almacen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferencia',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferencia',
            name='folio',
            field=models.CharField(default='default123', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='usuario',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferenciadetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferenciadetalle',
            name='producto_variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_detalle_variante', to='catalogo.productovariante'),
        ),
        migrations.AlterField(
            model_name='transferenciadetalle',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_detalle', to='catalogo.producto'),
        ),
    ]
