# Generated by Django 6.0.5 on 2026-07-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0003_historicaltransferencia_almacen_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransferencia',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('FALLIDA', 'Fallida')], default='COMPLETADA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('FALLIDA', 'Fallida')], default='COMPLETADA', max_length=50, null=True),
        ),
    ]
