# Generated by Django 6.0.5 on 2026-07-09 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0016_movimientoinventariodetalle_producto_variante'),
        ('wms', '0004_alter_historicaltransferencia_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciadetalle',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_detalle', to='inventarios.lote'),
        ),
        migrations.AlterField(
            model_name='transferenciadetalle',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_detalle', to='inventarios.serie'),
        ),
        migrations.AlterField(
            model_name='transferenciadetalle',
            name='ubicacion_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_detalle_destino', to='inventarios.ubicacion'),
        ),
        migrations.AlterField(
            model_name='transferenciadetalle',
            name='ubicacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_detalle_origen', to='inventarios.ubicacion'),
        ),
    ]
