# Generated by Django 6.0.5 on 2026-07-20 16:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_historicalcategoriaproducto_historicalproducto_and_more'),
        ('inventarios', '0017_alter_movimientoinventariodetalle_producto'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('wms', '0005_alter_transferenciadetalle_lote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='picking',
            name='almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pickings', to='inventarios.almacen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picking',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asignado', 'Asignado'), ('En proceso', 'En proceso'), ('Pausado', 'Pausado'), ('Completado', 'Completado'), ('Parcial', 'Parcial'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='picking',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picking',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picking',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picking',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picking',
            name='operador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pickings_operadores', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picking',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=50),
        ),
        migrations.AddField(
            model_name='picking',
            name='tipo',
            field=models.CharField(choices=[('ORDER_PICKING', 'Por pedido'), ('BATCH_PICKING', 'Por lote'), ('WAVE_PICKING', 'Por oleadas'), ('ZONE_PICKING', 'Por zonas')], default='ORDER_PICKING', max_length=50),
        ),
        migrations.AddField(
            model_name='picking',
            name='total_lineas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picking',
            name='total_lineas_completas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='picking',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pickings_usuarios', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickingdetalle',
            name='cantidad_asignada',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickingdetalle',
            name='cantidad_solicitada',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickingdetalle',
            name='cantidad_surtida',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickingdetalle',
            name='diferencia',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pickingdetalle',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SURTIDA', 'Surtida'), ('PARCIAL', 'Parcial'), ('FALTANTE', 'Faltante'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=50),
        ),
        migrations.AddField(
            model_name='pickingdetalle',
            name='fecha_surtido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickingdetalle',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picking_detalle', to='inventarios.lote'),
        ),
        migrations.AddField(
            model_name='pickingdetalle',
            name='motivo_diferencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pickingdetalle',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickingdetalle',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picking_detalle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickingdetalle',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picking_detalle', to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='pickingdetalle',
            name='producto_variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picking_detalle', to='catalogo.productovariante'),
        ),
        migrations.AddField(
            model_name='pickingdetalle',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='picking_detalle', to='inventarios.ubicacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickingdetalle',
            name='unidad_medida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='picking_detalle', to='nucleo.unidadmedida'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LotePicking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado'), ('EN_PROCESO', 'En proceso'), ('EN_SORTING', 'En clasificación'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=50)),
                ('total_pedidos', models.IntegerField(default=0)),
                ('total_lineas', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_picking', to='inventarios.almacen')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_picking', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_picking_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote Picking',
                'verbose_name_plural': 'Lotes Picking',
                'db_table': 'lotes_picking',
            },
        ),
        migrations.AddField(
            model_name='picking',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickings', to='wms.lotepicking'),
        ),
        migrations.CreateModel(
            name='Oleada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_liberacion', models.DateTimeField(blank=True, null=True)),
                ('criterio_agrupacion', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('LIBERADA', 'Liberada'), ('EN_PROCESO', 'En proceso'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=50)),
                ('total_pedidos', models.IntegerField(default=0)),
                ('total_lineas', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oleadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oleada',
                'verbose_name_plural': 'Oleadas',
                'db_table': 'oleadas',
            },
        ),
        migrations.AddField(
            model_name='picking',
            name='oleada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickings', to='wms.oleada'),
        ),
        migrations.CreateModel(
            name='ZonaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_zona', models.CharField(max_length=50)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_almacen', to='inventarios.almacen')),
            ],
            options={
                'verbose_name': 'Zona Almacen',
                'verbose_name_plural': 'Zonas Almacen',
                'db_table': 'zonas_almacen',
            },
        ),
        migrations.AddField(
            model_name='picking',
            name='zona_almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickings', to='wms.zonaalmacen'),
        ),
    ]
