# Generated by Django 6.0.5 on 2026-07-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0006_picking_almacen_picking_created_at_picking_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickingdetalle',
            name='unidad_medida',
        ),
    ]
