# Generated by Django 6.0.6 on 2026-07-22 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0018_inventario_reservas'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('wms', '0006_picking_almacen_picking_created_at_picking_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickingdetalle',
            name='unidad_medida',
        ),
        migrations.AddField(
            model_name='picking',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pickings', to='nucleo.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picking',
            name='folio',
            field=models.CharField(default='defaultfolio', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picking',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pickings', to='nucleo.sucursal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pickingdetalle',
            name='cantidad_asignada',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='pickingdetalle',
            name='cantidad_surtida',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='pickingdetalle',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picking_detalle', to='inventarios.ubicacion'),
        ),
    ]
