# Generated by Django 6.0.6 on 2026-07-24 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('ventas', '0040_cotizacion_tipo_pedido_and_more'),
        ('wms', '0007_remove_pickingdetalle_unidad_medida_picking_empresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='packing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packing',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packings', to='nucleo.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packing',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=50),
        ),
        migrations.AddField(
            model_name='packing',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packing',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packing',
            name='folio',
            field=models.CharField(default='defaultfolio', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packing',
            name='numero_cajas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packing',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packing',
            name='operador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packings_operadores', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packing',
            name='pedido',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='packings', to='ventas.pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packing',
            name='peso_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='packing',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packings', to='nucleo.sucursal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='packing',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packings_usuarios', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packing',
            name='volumen_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='packingdetalle',
            name='cantidad_empacada',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='packingdetalle',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=50),
        ),
        migrations.AddField(
            model_name='packingdetalle',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PackingCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('largo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ancho', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('alto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_cajas', to='wms.packing')),
            ],
        ),
        migrations.AddField(
            model_name='packingdetalle',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packing_detalle', to='wms.packingcaja'),
        ),
    ]
