# Generated by Django 6.0.6 on 2026-07-24 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0040_cotizacion_tipo_pedido_and_more'),
        ('wms', '0007_remove_pickingdetalle_unidad_medida_picking_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickingdetalle',
            name='pedido_detalle_talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picking_detalle', to='ventas.pedidodetalletalla'),
        ),
    ]
