# Generated by Django 6.0.5 on 2026-07-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0007_remove_pickingdetalle_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickingdetalle',
            name='cantidad_asignada',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='pickingdetalle',
            name='cantidad_surtida',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
