# Generated by Django 6.0.5 on 2026-07-21 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0017_alter_movimientoinventariodetalle_producto'),
        ('wms', '0008_alter_pickingdetalle_cantidad_asignada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickingdetalle',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picking_detalle', to='inventarios.ubicacion'),
        ),
    ]
