# Generated by Django 6.0.6 on 2026-07-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0008_packing_created_at_packing_empresa_packing_estado_and_more'),
        ('wms', '0008_pickingdetalle_pedido_detalle_talla'),
    ]

    operations = [
    ]
