# Generated by Django 6.0.5 on 2026-07-21 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('wms', '0009_alter_pickingdetalle_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='picking',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pickings', to='nucleo.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picking',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pickings', to='nucleo.sucursal'),
            preserve_default=False,
        ),
    ]
