# Generated by Django 6.0.4 on 2026-07-27 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
        ('wms', '0009_merge_20260727_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='logistica.envio'),
        ),
    ]
