# Generated by Django 6.0.5 on 2026-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0010_picking_empresa_picking_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='picking',
            name='folio',
            field=models.CharField(default='defaultfolio', max_length=50),
            preserve_default=False,
        ),
    ]
