# Generated by Django 6.0.6 on 2026-07-28 20:24

import django.db.models.deletion
from django.db import migrations, models


def _asignar_almacen_destino_apartados(apps, schema_editor):
    Picking = apps.get_model("wms", "Picking")
    Almacen = apps.get_model("inventarios", "Almacen")

    apartados_por_contexto = {}
    for picking in Picking.objects.select_related(
        "pedido__empresa", "pedido__sucursal"
    ).filter(almacen_destino__isnull=True).iterator(chunk_size=500):
        empresa_id = getattr(getattr(picking.pedido, "empresa", None), "pk", None)
        sucursal_id = getattr(getattr(picking.pedido, "sucursal", None), "pk", None)
        if not empresa_id or not sucursal_id:
            continue
        key = (empresa_id, sucursal_id)
        almacen_apartados = apartados_por_contexto.get(key)
        if almacen_apartados is None:
            almacen_apartados = (
                Almacen.objects.filter(
                    nombre__iexact="APARTADOS",
                    empresa_id=empresa_id,
                    sucursal_id=sucursal_id,
                )
                .order_by("pk")
                .first()
            )
            apartados_por_contexto[key] = almacen_apartados
        if almacen_apartados is not None:
            picking.almacen_destino = almacen_apartados
            picking.save(update_fields=["almacen_destino"])


def _noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0019_inventario_reservas_almacen_and_more'),
        ('produccion', '0020_historicalordenproduccion_and_more'),
        ('wms', '0010_alter_despacho_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='picking',
            name='almacen_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickings_destino', to='inventarios.almacen'),
        ),
        migrations.CreateModel(
            name='PickingOrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_orden', models.CharField(choices=[('BORDADO', 'Bordado'), ('REFLEJANTE', 'Reflejante'), ('CORTE_MANGA', 'Corte de manga')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orden_bordado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picking_ordenes_trabajo', to='produccion.ordenesbordado')),
                ('orden_corte_manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picking_ordenes_trabajo', to='produccion.ordenescortemanga')),
                ('orden_reflejante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picking_ordenes_trabajo', to='produccion.ordenesreflejante')),
                ('picking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='wms.picking')),
            ],
            options={
                'verbose_name': 'Picking Orden Trabajo',
                'verbose_name_plural': 'Picking Ordenes Trabajo',
                'db_table': 'picking_orden_trabajo',
            },
        ),
        migrations.RunPython(
            _asignar_almacen_destino_apartados,
            _noop_reverse,
        ),
    ]
