# Generated by Django 6.0.4 on 2026-07-31 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_historicalcategoriaproducto_historicalproducto_and_more'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('wms', '0011_picking_almacen_destino_orden_trabajo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaRFIDImpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('rfid_mode', models.BooleanField(default=True)),
                ('printer_name', models.CharField(blank=True, max_length=128, null=True)),
                ('printer_address', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EXITO', 'Éxito'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=16)),
                ('zpl_enviado', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas_rfid_impresiones', to='nucleo.empresa')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas_rfid_impresiones', to='catalogo.producto')),
                ('producto_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas_rfid_impresiones', to='catalogo.productovariante')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas_rfid_impresiones', to='nucleo.sucursal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas_rfid_impresiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impresión Etiqueta RFID',
                'verbose_name_plural': 'Impresiones Etiquetas RFID',
                'db_table': 'etiquetas_rfid_impresiones',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EtiquetaRFIDDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc', models.CharField(db_index=True, max_length=64, unique=True)),
                ('barcode_value', models.CharField(max_length=128)),
                ('serial', models.CharField(blank=True, max_length=64, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('IMPRESO', 'Impreso'), ('LEIDO', 'Leído'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('impresion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='wms.etiquetarfidimpresion')),
            ],
            options={
                'verbose_name': 'Detalle Etiqueta RFID',
                'verbose_name_plural': 'Detalles Etiquetas RFID',
                'db_table': 'etiquetas_rfid_detalle',
                'ordering': ['impresion_id', 'id'],
            },
        ),
    ]
