# Generated by Django 6.0.6 on 2026-08-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0012_etiquetarfidimpresion_etiquetarfiddetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfidScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epc', models.CharField(db_index=True, max_length=255)),
                ('reader_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('antenna', models.IntegerField(blank=True, null=True)),
                ('rssi', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lectura RFID',
                'verbose_name_plural': 'Lecturas RFID',
                'db_table': 'rfid_scans',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
