# Generated by Django 6.0.4 on 2026-10-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0013_add_rfidscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='guia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
