# Generated by Django 6.0.7 on 2026-10-06 15:50

import django.db.models.deletion
import wms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('wms', '0014_despacho_guia'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidscan',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid_scans', to='nucleo.empresa'),
        ),
        migrations.CreateModel(
            name='LectorRFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('token', models.CharField(default=wms.models._generar_token_lector, max_length=64, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('ultima_lectura', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectores_rfid', to='nucleo.empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lectores_rfid', to='nucleo.sucursal')),
            ],
            options={
                'verbose_name': 'Lector RFID',
                'verbose_name_plural': 'Lectores RFID',
                'db_table': 'lectores_rfid',
                'ordering': ['empresa_id', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='rfidscan',
            name='lector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='wms.lectorrfid'),
        ),
    ]
