# Generated by Django 6.0.7 on 2026-10-06 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('wms', '0015_lector_rfid_y_empresa_en_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectorrfid',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lectores_rfid', to='nucleo.sucursal'),
        ),
    ]
