# Generated by Django 5.2 on 2026-02-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_empresa', models.BigIntegerField(db_index=True)),
                ('id_sucursal_default', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('is_admin_empresa', models.BooleanField(default=False)),
                ('estatus', models.PositiveSmallIntegerField(choices=[(3, 'Suspendido'), (2, 'Bloqueado'), (1, 'Activo')], default=1)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('preferencias_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'indexes': [models.Index(fields=['id_empresa'], name='idx_usuario_empresa'), models.Index(fields=['estatus'], name='idx_usuario_estatus')],
                'constraints': [models.UniqueConstraint(fields=('id_empresa', 'username'), name='uq_usuario_username_empresa'), models.UniqueConstraint(fields=('id_empresa', 'email'), name='uq_usuario_email_empresa')],
            },
        ),
    ]
