# Generated by Django 5.2 on 2026-02-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_satclaveprodserv_satclaveunidad_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sucursales',
            field=models.ManyToManyField(blank=True, help_text='Sucursales a las que el usuario tiene acceso para operar.', related_name='usuarios_permitidos', to='nucleo.sucursal'),
        ),
    ]
