# Generated by Django 5.2 on 2026-02-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_satclaveprodserv_satclaveunidad_and_more'),
        ('usuarios', '0002_usuario_sucursales'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='departamentos',
            field=models.ManyToManyField(blank=True, help_text='Departamentos específicos a los que el usuario tiene acceso.', related_name='usuarios_permitidos', to='nucleo.departamento'),
        ),
    ]
