# Generated by Django 6.0.2 on 2026-02-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_alter_empresasatconfig_regimen_fiscal'),
        ('usuarios', '0003_usuario_departamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empresas',
            field=models.ManyToManyField(blank=True, help_text='Empresas a las que el usuario tiene acceso.', related_name='usuarios_autorizados', to='nucleo.empresa'),
        ),
    ]
