# Generated by Django 6.0.2 on 2026-02-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_empresas'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usuario',
            name='usuarios_empresa_fe0e9f_idx',
        ),
    ]
