# Generated by Django 6.0.2 on 2026-02-16 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
        ('nucleo', '0008_remove_departamento_departament_empresa_a3883d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='id_sucursal',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='id_almacen',
        ),
        migrations.AddField(
            model_name='almacen',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='almacen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='almacen',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='almacenes', to='nucleo.empresa'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='estatus',
            field=models.CharField(default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='almacen',
            name='nombre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='almacen',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='almacenes', to='nucleo.sucursal'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='inventarios.almacen'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='nucleo.empresa'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='estatus',
            field=models.CharField(default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='nucleo.sucursal'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='almacen',
            index=models.Index(fields=['empresa', 'estatus'], name='almacenes_empresa_933809_idx'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['empresa', 'estatus'], name='ubicaciones_empresa_b9fd22_idx'),
        ),
        migrations.AddConstraint(
            model_name='almacen',
            constraint=models.UniqueConstraint(fields=('sucursal', 'codigo'), name='uq_almacen_sucursal_codigo'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.UniqueConstraint(fields=('almacen', 'codigo'), name='uq_ubicacion_almacen_codigo'),
        ),
    ]
