# Generated by Django 6.0.2 on 2026-02-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_remove_almacen_id_sucursal_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ubicacion',
            name='uq_ubicacion_almacen_codigo',
        ),
        migrations.RemoveIndex(
            model_name='ubicacion',
            name='ubicaciones_empresa_b9fd22_idx',
        ),
        migrations.RenameField(
            model_name='ubicacion',
            old_name='codigo',
            new_name='nivel',
        ),
        migrations.AddField(
            model_name='almacen',
            name='permite_entrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='almacen',
            name='permite_salida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='almacen',
            name='permite_transferencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='almacen',
            name='requiere_ubicacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='almacen',
            name='tipo_almacen',
            field=models.CharField(choices=[('MP', 'Materia Prima'), ('PT', 'Producto Terminado'), ('PROCESO', 'En Proceso'), ('CUARENTENA', 'Cuarentena'), ('DEVOLUCION', 'Devolucion'), ('TRANSITO', 'Transito')], default='MP', max_length=20),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='bloqueada_entrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='bloqueada_salida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='orden_recorrido',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='pasillo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='permite_mezcla_lotes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='permite_mezcla_productos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='posicion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='rack',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='tipo_ubicacion',
            field=models.CharField(choices=[('RECIBO', 'Recibo'), ('PICKING', 'Picking'), ('RESERVA', 'Reserva'), ('STAGING', 'Staging'), ('EMBARQUE', 'Embarque'), ('CUARENTENA', 'Cuarentena'), ('DEVOLUCION', 'Devolucion')], default='RESERVA', max_length=20),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.UniqueConstraint(fields=('almacen', 'pasillo', 'rack', 'nivel', 'posicion'), name='uq_ubicacion_coords'),
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='sucursal',
        ),
    ]
