# Generated by Django 6.0.2 on 2026-02-27 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_color_talla_categoriaproducto_activo_and_more'),
        ('inventarios', '0003_remove_ubicacion_uq_ubicacion_almacen_codigo_and_more'),
        ('nucleo', '0009_seriefolio_incluir_anio_seriefolio_reiniciar_anual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_inventario', to='inventarios.almacen')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_inventario', to='nucleo.empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_inventario', to='nucleo.sucursal')),
            ],
            options={
                'verbose_name': 'Ajuste Inventario',
                'verbose_name_plural': 'Ajustes Inventario',
                'db_table': 'ajustes_inventario',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='catalogo.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencia', to='inventarios.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencia', to='catalogo.producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencia', to='inventarios.ubicacion')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencia', to='inventarios.lote')),
            ],
            options={
                'verbose_name': 'Existencia',
                'verbose_name_plural': 'Existencia',
                'db_table': 'existencias',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajuste_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='inventarios.ajusteinventario')),
            ],
            options={
                'verbose_name': 'Movimiento Inventario',
                'verbose_name_plural': 'Movimientos Inventario',
                'db_table': 'movimientos_inventario',
            },
        ),
    ]
