# Generated by Django 6.0.2 on 2026-02-27 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_color_talla_categoriaproducto_activo_and_more'),
        ('inventarios', '0004_serie_ajusteinventario_lote_existencia_and_more'),
        ('nucleo', '0009_seriefolio_incluir_anio_seriefolio_reiniciar_anual_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='devolucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='ventas.devolucion'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='nucleo.empresa'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='entrega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='ventas.entrega'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='ventas.pedido'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='nucleo.sucursal'),
        ),
        migrations.AddField(
            model_name='serie',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='existencia',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencia', to='inventarios.serie'),
        ),
    ]
