# Generated by Django 6.0.2 on 2026-03-02 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_color_talla_categoriaproducto_activo_and_more'),
        ('inventarios', '0005_movimientoinventario_devolucion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventarioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_movimieinto_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventarios.movimientoinventario')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario_detalle', to='inventarios.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario_detalle', to='catalogo.producto')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario_detalle', to='inventarios.serie')),
                ('ubicacion_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario_detalle_destino', to='inventarios.ubicacion')),
                ('ubicacion_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario_detalle_origen', to='inventarios.ubicacion')),
            ],
        ),
    ]
