# Generated by Django 6.0.2 on 2026-03-02 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_color_talla_categoriaproducto_activo_and_more'),
        ('inventarios', '0006_movimientoinventariodetalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoinventariodetalle',
            options={'verbose_name': 'Movimiento Inventario Detalle', 'verbose_name_plural': 'Movimientos Inventario Detalle'},
        ),
        migrations.RenameField(
            model_name='movimientoinventariodetalle',
            old_name='id_movimieinto_inventario',
            new_name='movimiento_inventario',
        ),
        migrations.AlterField(
            model_name='movimientoinventariodetalle',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_inventario_detalle', to='inventarios.lote'),
        ),
        migrations.AlterField(
            model_name='movimientoinventariodetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_inventario_detalle', to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='movimientoinventariodetalle',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_inventario_detalle', to='inventarios.serie'),
        ),
        migrations.AlterField(
            model_name='movimientoinventariodetalle',
            name='ubicacion_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_inventario_detalle_destino', to='inventarios.ubicacion'),
        ),
        migrations.AlterField(
            model_name='movimientoinventariodetalle',
            name='ubicacion_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_inventario_detalle_origen', to='inventarios.ubicacion'),
        ),
        migrations.AlterModelTable(
            name='movimientoinventariodetalle',
            table='movimiento_inventario_detalle',
        ),
    ]
