# Generated by Django 6.0.2 on 2026-04-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0007_alter_movimientoinventariodetalle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='tipo_ubicacion',
            field=models.CharField(choices=[('INVENTARIO', 'Inventario'), ('RECIBO', 'Recibo'), ('PICKING', 'Picking'), ('RESERVA', 'Reserva'), ('STAGING', 'Staging'), ('EMBARQUE', 'Embarque'), ('CUARENTENA', 'Cuarentena'), ('DEVOLUCION', 'Devolucion')], default='RESERVA', max_length=20),
        ),
    ]
