# Generated by Django 6.0.4 on 2026-05-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0008_alter_ubicacion_tipo_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='existencia',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
