# Generated by Django 6.0.4 on 2026-05-06 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_producto_codigo'),
        ('inventarios', '0009_existencia_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='existencia',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='existencia',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='existencia',
            name='serie',
        ),
        migrations.AddField(
            model_name='existencia',
            name='producto_variante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='existencia', to='catalogo.productovariante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='existencia',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='existencia', to='inventarios.ubicacion'),
        ),
    ]
