# Generated by Django 6.0.5 on 2026-06-08 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_productovariante_nombre'),
        ('inventarios', '0010_remove_existencia_lote_remove_existencia_producto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteinventario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ajusteinventario',
            name='fecha_ajuste',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ajusteinventario',
            name='motivo',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ajusteinventario',
            name='observaciones',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ajusteinventario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existencia',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existencia',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='fecha_movimiento',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='observaciones',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('TRANSFERENCIA', 'Transferencia')], default='ENTRADA', max_length=50),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoinventariodetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='movimientoinventariodetalle',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.CreateModel(
            name='AjusteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sistema', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cantidad_fisica', models.DecimalField(decimal_places=4, max_digits=18)),
                ('diferencia', models.DecimalField(decimal_places=4, max_digits=18)),
                ('ajuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.ajusteinventario')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.serie')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.ubicacion')),
            ],
            options={
                'verbose_name': 'Ajuste detalle',
                'verbose_name_plural': 'Ajustes Detalle',
                'db_table': 'ajuste_detalle',
            },
        ),
    ]
