# Generated by Django 6.0.5 on 2026-06-08 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_ordencompra_folio_alter_ordencompra_pedido_and_more'),
        ('inventarios', '0011_ajusteinventario_activo_and_more'),
        ('produccion', '0010_ordenescortemanga_ordencortemangadetalle'),
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='op',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='recepcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.recepcion'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='transferencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wms.transferencia'),
        ),
    ]
