# Generated by Django 5.2 on 2026-06-16 22:31

import django.db.models.deletion
from django.db import migrations, models


def backfill_existencia_producto(apps, schema_editor):
    Existencia = apps.get_model('inventarios', 'Existencia')
    batch = []
    for existencia in (
        Existencia.objects.exclude(producto_variante__isnull=True)
        .filter(producto__isnull=True)
        .select_related('producto_variante__producto')
        .iterator()
    ):
        producto = getattr(existencia.producto_variante, 'producto', None)
        if not producto:
            continue
        existencia.producto_id = producto.pk
        batch.append(existencia)

    if batch:
        Existencia.objects.bulk_update(batch, ['producto'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_producto_tipo'),
        ('inventarios', '0012_movimientoinventario_op_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='existencia',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='producto_variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='existencia', to='catalogo.productovariante'),
        ),
        migrations.RunPython(backfill_existencia_producto, migrations.RunPython.noop),
    ]
