# Generated by Django 5.2 on 2026-06-26 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_alter_recepciondetalle_ubicacion'),
        ('inventarios', '0013_existencia_producto_and_more'),
        ('produccion', '0017_alter_ordenproducciondetalle_op'),
        ('ventas', '0038_alter_cotizacion_cliente_and_more'),
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='ajuste_inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='inventarios.ajusteinventario'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='devolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='ventas.devolucion'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='ventas.entrega'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='op',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenproduccion'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='ventas.pedido'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.recepcion'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='transferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wms.transferencia'),
        ),
        migrations.AlterField(
            model_name='movimientoinventariodetalle',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_inventario_detalle', to='inventarios.lote'),
        ),
        migrations.AlterField(
            model_name='movimientoinventariodetalle',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_inventario_detalle', to='inventarios.serie'),
        ),
        migrations.AlterField(
            model_name='movimientoinventariodetalle',
            name='ubicacion_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_inventario_detalle_destino', to='inventarios.ubicacion'),
        ),
        migrations.AlterField(
            model_name='movimientoinventariodetalle',
            name='ubicacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_inventario_detalle_origen', to='inventarios.ubicacion'),
        ),
    ]
