# Generated by Django 6.0.5 on 2026-07-09 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_historicalcategoriaproducto_historicalproducto_and_more'),
        ('inventarios', '0015_historicalajusteinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventariodetalle',
            name='producto_variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_detalle', to='catalogo.productovariante'),
        ),
    ]
