# Generated by Django 6.0.5 on 2026-07-16 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_historicalcategoriaproducto_historicalproducto_and_more'),
        ('inventarios', '0016_movimientoinventariodetalle_producto_variante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventariodetalle',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_inventario_detalle', to='catalogo.producto'),
        ),
    ]
