# Generated by Django 6.0.4 on 2026-07-21 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0017_alter_movimientoinventariodetalle_producto'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('ventas', '0040_cotizacion_tipo_pedido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='inventario_reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_devolucion', models.DateTimeField(auto_now=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_reservas', to='nucleo.empresa')),
                ('pedido_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_reservas', to='ventas.pedidodetalle')),
                ('pedido_detalle_talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_reservas', to='ventas.pedidodetalletalla')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventario_reservas', to='nucleo.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventario Reserva',
                'verbose_name_plural': 'Inventario Reservas',
                'db_table': 'inventario_reservas',
            },
        ),
    ]
