# Generated by Django 6.0.6 on 2026-07-24 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0018_inventario_reservas'),
        ('wms', '0007_remove_pickingdetalle_unidad_medida_picking_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_reservas',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventario_reservas', to='inventarios.almacen'),
        ),
        migrations.AddField(
            model_name='inventario_reservas',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('APLICADA', 'Aplicada'), ('LIBERADA', 'Liberada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20),
        ),
        migrations.AddField(
            model_name='inventario_reservas',
            name='existencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventario_reservas', to='inventarios.existencia'),
        ),
        migrations.AddField(
            model_name='inventario_reservas',
            name='fecha_aplicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario_reservas',
            name='observaciones',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='inventario_reservas',
            name='picking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_inventario', to='wms.picking'),
        ),
        migrations.AddField(
            model_name='inventario_reservas',
            name='transferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_inventario', to='wms.transferencia'),
        ),
        migrations.AddField(
            model_name='inventario_reservas',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventario_reservas', to='inventarios.ubicacion'),
        ),
        migrations.AlterField(
            model_name='inventario_reservas',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
