# Generated by Django 5.2 on 2026-04-06 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google_drive', 'Google Drive'), ('dropbox', 'Dropbox'), ('onedrive', 'OneDrive'), ('box', 'Box')], max_length=30)),
                ('account_email', models.EmailField(blank=True, max_length=254)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cloud Integration',
                'verbose_name_plural': 'Cloud Integrations',
                'db_table': 'ia_cloud_integrations',
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='uniq_cloud_integration_user_provider')],
            },
        ),
    ]
