# Generated by Django 5.2 on 2026-02-03 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariorol',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='rolpermiso',
            constraint=models.UniqueConstraint(fields=('rol', 'permiso'), name='uq_rol_permiso'),
        ),
        migrations.AddIndex(
            model_name='rol',
            index=models.Index(fields=['empresa', 'estatus'], name='roles_empresa_76d184_idx'),
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_rol_empresa_codigo'),
        ),
        migrations.AddIndex(
            model_name='usuariorol',
            index=models.Index(fields=['empresa'], name='usuarios_ro_empresa_3fe898_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariorol',
            index=models.Index(fields=['usuario'], name='usuarios_ro_usuario_5cf550_idx'),
        ),
        migrations.AddConstraint(
            model_name='usuariorol',
            constraint=models.UniqueConstraint(fields=('usuario', 'rol'), name='uq_usuario_rol'),
        ),
    ]
