# Generated by Django 4.2.27 on 2026-01-28 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0001_initial'),
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariorol',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolpermiso',
            name='permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_roles', to='seguridad.permiso'),
        ),
        migrations.AddField(
            model_name='rolpermiso',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_permisos', to='seguridad.rol'),
        ),
        migrations.AddField(
            model_name='rol',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='nucleo.empresa'),
        ),
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(related_name='roles', through='seguridad.RolPermiso', to='seguridad.permiso'),
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['modulo'], name='permisos_modulo_b603c7_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariorol',
            index=models.Index(fields=['empresa'], name='usuarios_ro_empresa_3fe898_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariorol',
            index=models.Index(fields=['usuario'], name='usuarios_ro_usuario_5cf550_idx'),
        ),
        migrations.AddConstraint(
            model_name='usuariorol',
            constraint=models.UniqueConstraint(fields=('usuario', 'rol'), name='uq_usuario_rol'),
        ),
        migrations.AddConstraint(
            model_name='rolpermiso',
            constraint=models.UniqueConstraint(fields=('rol', 'permiso'), name='uq_rol_permiso'),
        ),
        migrations.AddIndex(
            model_name='rol',
            index=models.Index(fields=['empresa', 'estatus'], name='roles_empresa_76d184_idx'),
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_rol_empresa_codigo'),
        ),
    ]
