# Generated by Django 5.2 on 2026-02-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='clave_departamento',
            field=models.CharField(blank=True, help_text="Código del departamento al que este rol da acceso automáticamente (ej. 'VENTAS').", max_length=50, null=True),
        ),
    ]
