# Generated by Django 6.0.2 on 2026-02-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_rol_clave_departamento'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usuariorol',
            name='usuarios_ro_empresa_3fe898_idx',
        ),
        migrations.RemoveIndex(
            model_name='usuariorol',
            name='usuarios_ro_usuario_5cf550_idx',
        ),
    ]
