# Generated by Django 6.0.2 on 2026-02-24 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_remove_departamento_departament_empresa_a3883d_idx_and_more'),
        ('seguridad', '0004_remove_usuariorol_usuarios_ro_empresa_3fe898_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('grant', 'Grant (Otorgar)'), ('deny', 'Deny (Denegar)')], default='grant', help_text='Grant: Otorga el permiso aunque no lo tenga por rol. Deny: Revoca el permiso aunque lo tenga por rol.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.empresa')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides_usuarios', to='seguridad.permiso')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides_permisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Permiso (Override)',
                'verbose_name_plural': 'Usuarios Permisos (Overrides)',
                'db_table': 'usuarios_permisos',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'permiso', 'empresa', 'sucursal'), name='uq_usuario_permiso_override')],
            },
        ),
    ]
