# Generated by Django 6.0.2 on 2026-03-04 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0004_alter_tipoproducto_codigo'),
        ('inventarios', '0007_alter_movimientoinventariodetalle_options_and_more'),
        ('nucleo', '0009_seriefolio_incluir_anio_seriefolio_reiniciar_anual_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaMaterialBom',
            fields=[
                ('bom_id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Lista Material bom',
                'verbose_name_plural': 'Listas Materiales bom',
                'db_table': 'listas_materiales_bom',
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('op_id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.empresa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pedido')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.sucursal')),
            ],
            options={
                'verbose_name': 'Orden Produccion',
                'verbose_name_plural': 'Ordenes Produccion',
                'db_table': 'ordenes_produccion',
            },
        ),
        migrations.CreateModel(
            name='ConsumoProduccion',
            fields=[
                ('consumo_produccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenproduccion')),
            ],
            options={
                'verbose_name': 'Consumo Produccion',
                'verbose_name_plural': 'Consumos Produccion',
                'db_table': 'consumos_produccion',
            },
        ),
        migrations.CreateModel(
            name='ProductoTerminadoEntradas',
            fields=[
                ('pt_entrada_id', models.AutoField(primary_key=True, serialize=False)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.almacen')),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenproduccion')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.ubicacion')),
            ],
            options={
                'verbose_name': 'Producto Terminado Entrada',
                'verbose_name_plural': 'Producto Terminado Entradas',
                'db_table': 'producto_terminado_entradas',
            },
        ),
        migrations.CreateModel(
            name='RutaProduccion',
            fields=[
                ('ruta_produccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Ruta Produccion',
                'verbose_name_plural': 'Rutas Produccion',
                'db_table': 'rutas_produccion',
            },
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='ruta_produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.rutaproduccion'),
        ),
    ]
