# Generated by Django 6.0.5 on 2026-05-15 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_productovariante_nombre'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('produccion', '0001_initial'),
        ('ventas', '0034_cotizacionservicioextra_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenesBordado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_bordado', models.CharField(max_length=50, unique=True)),
                ('estatus_bordado', models.IntegerField(default=1)),
                ('prioridad', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.empresa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pedido')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.sucursal')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden Bordado',
                'verbose_name_plural': 'Ordenes Bordado',
                'db_table': 'orden_bordado',
            },
        ),
        migrations.CreateModel(
            name='OrdenBordadoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('posicion_bordado', models.CharField(max_length=50)),
                ('colores_hilo', models.IntegerField(default=0)),
                ('puntadas', models.IntegerField(default=0)),
                ('pedido_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pedidodetalle')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
                ('ob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenesbordado')),
            ],
            options={
                'verbose_name': 'Orden Bordado Detalle',
                'verbose_name_plural': 'Ordenes Bordado Detalle',
                'db_table': 'orden_bordado_detalle',
            },
        ),
        migrations.CreateModel(
            name='BordadoIncidencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidencia', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenesbordado')),
            ],
            options={
                'verbose_name': 'Bordado Incidencia',
                'verbose_name_plural': 'Bordado Incidencias',
                'db_table': 'bordado_incidencias',
            },
        ),
        migrations.CreateModel(
            name='BordadoAvances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad_bordada', models.FloatField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenesbordado')),
            ],
            options={
                'verbose_name': 'Bordado Avance',
                'verbose_name_plural': 'Bordado Avances',
                'db_table': 'bordado_avances',
            },
        ),
    ]
