# Generated by Django 6.0.4 on 2026-05-15 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_ordenesbordado_ordenbordadodetalle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenesbordado',
            name='estatus_bordado',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Preparacion'), (3, 'Bordando'), (4, 'Revision'), (5, 'Completado'), (6, 'Detenido'), (7, 'Cancelado')], default=1),
        ),
        migrations.AlterField(
            model_name='ordenesbordado',
            name='usuario_asignado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
