# Generated by Django 6.0.4 on 2026-05-15 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_productovariante_nombre'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('produccion', '0003_alter_ordenesbordado_estatus_bordado_and_more'),
        ('ventas', '0034_cotizacionservicioextra_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenesReflejante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_reflejante', models.CharField(max_length=50, unique=True)),
                ('estatus_reflejante', models.IntegerField()),
                ('prioridad', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.empresa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pedido')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.sucursal')),
            ],
            options={
                'verbose_name': 'Orden Reflejante',
                'verbose_name_plural': 'Ordenes Reflejante',
                'db_table': 'orden_reflejante',
            },
        ),
        migrations.CreateModel(
            name='OrdenReflejanteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('tipo_reflejante', models.CharField(max_length=50)),
                ('posicion', models.CharField(max_length=50)),
                ('metros', models.FloatField()),
                ('orden_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenesreflejante')),
                ('pedido_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pedidodetalle')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Orden Reflejante Detalle',
                'verbose_name_plural': 'Ordenes Reflejante Detalle',
                'db_table': 'orden_reflejante_detalle',
            },
        ),
        migrations.CreateModel(
            name='ReflejanteAvances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad_aplicada', models.FloatField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenesreflejante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reflejante Avance',
                'verbose_name_plural': 'Reflejante Avances',
                'db_table': 'reflejante_avances',
            },
        ),
        migrations.CreateModel(
            name='ReflejanteIncidencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenesreflejante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reflejante Incidencia',
                'verbose_name_plural': 'Reflejante Incidencias',
                'db_table': 'reflejante_incidencias',
            },
        ),
    ]
