# Generated by Django 5.2 on 2026-05-20 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_productovariante_nombre'),
        ('produccion', '0004_ordenesreflejante_ordenreflejantedetalle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenbordadodetalle',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.color'),
        ),
        migrations.AddField(
            model_name='ordenbordadodetalle',
            name='talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.talla'),
        ),
        migrations.AlterField(
            model_name='ordenbordadodetalle',
            name='ob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.ordenesbordado'),
        ),
        migrations.AlterField(
            model_name='ordenbordadodetalle',
            name='posicion_bordado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenesbordado',
            name='prioridad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordenesbordado',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
