# Generated by Django 5.2 on 2026-05-20 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_productovariante_nombre'),
        ('produccion', '0005_ordenbordadodetalle_color_ordenbordadodetalle_talla_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenesreflejante',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenreflejantedetalle',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.color'),
        ),
        migrations.AddField(
            model_name='ordenreflejantedetalle',
            name='talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.talla'),
        ),
        migrations.AlterField(
            model_name='ordenesreflejante',
            name='estatus_reflejante',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Preparacion'), (3, 'Aplicando'), (4, 'Revision'), (5, 'Completado'), (6, 'Detenido'), (7, 'Cancelado')], default=1),
        ),
        migrations.AlterField(
            model_name='ordenesreflejante',
            name='prioridad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordenreflejantedetalle',
            name='metros',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordenreflejantedetalle',
            name='orden_r',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.ordenesreflejante'),
        ),
        migrations.AlterField(
            model_name='ordenreflejantedetalle',
            name='posicion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenreflejantedetalle',
            name='tipo_reflejante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
