# Generated by Django 6.0.5 on 2026-05-22 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_productovariante_nombre'),
        ('produccion', '0006_ordenesreflejante_usuario_asignado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenproduccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Orden Produccion Detalle',
                'verbose_name_plural': 'Ordenes Produccion Detalle',
                'db_table': 'orden_produccion_detalle',
            },
        ),
    ]
