# Generated by Django 6.0.5 on 2026-05-25 13:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_ordenproducciondetalle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='estatus_op',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Preparacion'), (3, 'En produccion'), (4, 'Revision'), (5, 'Completado'), (6, 'Detenido'), (7, 'Cancelado')], default=1),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='folio_op',
            field=models.CharField(default='default', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='prioridad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OrdenProduccionDetalle',
        ),
    ]
