# Generated by Django 6.0.4 on 2026-05-25 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_ordenproduccion_activo_ordenproduccion_estatus_op_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproduccion',
            name='ruta_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produccion.rutaproduccion'),
        ),
    ]
