# Generated by Django 5.2 on 2026-05-25 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_productovariante_nombre'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('produccion', '0009_alter_ordenproduccion_ruta_produccion'),
        ('ventas', '0037_cotizaciondetalletalla_variante_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenesCorteManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_ocm', models.CharField(max_length=50, unique=True)),
                ('estatus_corte', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Preparacion'), (3, 'Cortando'), (4, 'Revision'), (5, 'Completado'), (6, 'Detenido'), (7, 'Cancelado')], default=1)),
                ('prioridad', models.IntegerField(default=1)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.empresa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pedido')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.sucursal')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden Corte Manga',
                'verbose_name_plural': 'Ordenes Corte Manga',
                'db_table': 'orden_corte_manga',
            },
        ),
        migrations.CreateModel(
            name='OrdenCorteMangaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('configuracion', models.JSONField(blank=True, null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.color')),
                ('pedido_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pedidodetalle')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
                ('talla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.talla')),
                ('ocm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.ordenescortemanga')),
            ],
            options={
                'verbose_name': 'Orden Corte Manga Detalle',
                'verbose_name_plural': 'Ordenes Corte Manga Detalle',
                'db_table': 'orden_corte_manga_detalle',
            },
        ),
    ]
