# Generated by Django 5.2 on 2026-06-18 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_producto_tipo'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('produccion', '0010_ordenescortemanga_ordencortemangadetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='listamaterialbom',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listamaterialbom',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listamaterialbom',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='BomDetalle',
            fields=[
                ('bom_detalle_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('desperdicio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('obligatorio', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.listamaterialbom')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.unidadmedida')),
            ],
            options={
                'verbose_name': 'Bom Detalle',
                'verbose_name_plural': 'Bom Detalles',
                'db_table': 'bom_detalles',
            },
        ),
    ]
