# Generated by Django 5.2 on 2026-06-18 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_producto_tipo'),
        ('produccion', '0011_listamaterialbom_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomdetalle',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='listamaterialbom',
            name='producto',
        ),
        migrations.AddField(
            model_name='bomdetalle',
            name='producto_variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.productovariante'),
        ),
        migrations.AddField(
            model_name='bomdetalle',
            name='variante_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.varianteproductoproduccion'),
        ),
        migrations.AddField(
            model_name='listamaterialbom',
            name='producto_variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.productovariante'),
        ),
        migrations.AddField(
            model_name='listamaterialbom',
            name='variante_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.varianteproductoproduccion'),
        ),
    ]
