# Generated by Django 5.2 on 2026-06-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0012_remove_bomdetalle_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomdetalle',
            name='orden',
        ),
    ]
