# Generated by Django 6.0.5 on 2026-06-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_producto_tipo'),
        ('produccion', '0013_remove_bomdetalle_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomdetalle',
            name='producto_variante',
        ),
        migrations.AddField(
            model_name='bomdetalle',
            name='componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_componentes', to='catalogo.producto'),
        ),
    ]
