# Generated by Django 6.0.5 on 2026-06-19 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0014_remove_bomdetalle_producto_variante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomdetalle',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_prima_detalle', to='produccion.listamaterialbom'),
        ),
    ]
