# Generated by Django 5.2 on 2026-06-22 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_producto_tipo'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('produccion', '0015_alter_bomdetalle_bom'),
        ('ventas', '0038_alter_cotizacion_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproduccion',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.pedido'),
        ),
        migrations.CreateModel(
            name='OrdenProduccionDetalle',
            fields=[
                ('op_detalle_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.listamaterialbom')),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenproduccion')),
                ('pedido_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.pedidodetalle')),
                ('producto_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.productovariante')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.unidadmedida')),
            ],
            options={
                'verbose_name': 'Orden Produccion Detalle',
                'verbose_name_plural': 'Ordenes Produccion Detalles',
                'db_table': 'ordenes_produccion_detalles',
            },
        ),
    ]
