# Generated by Django 6.0.5 on 2026-06-22 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0016_alter_ordenproduccion_pedido_ordenproducciondetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproducciondetalle',
            name='op',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_produccion_detalle', to='produccion.ordenproduccion'),
        ),
    ]
