# Generated by Django 5.2 on 2026-06-30 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_producto_tipo'),
        ('produccion', '0017_alter_ordenproducciondetalle_op'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoProduccionDetalle',
            fields=[
                ('consumo_detalle_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('consumo_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.consumoproduccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Consumo Produccion Detalle',
                'verbose_name_plural': 'Consumos Produccion Detalle',
                'db_table': 'consumo_detalle',
            },
        ),
    ]
