# Generated by Django 5.2 on 2026-07-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0018_consumoproducciondetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='cerrar_orden',
            field=models.BooleanField(default=False),
        ),
    ]
