# Generated by Django 6.0.5 on 2026-08-03 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Índice único parcial: una sola OrdenesReflejante activa por pedido.

    OJO al aplicar sobre datos existentes: si ya hay dos o más OR con
    ``activo=True`` para el mismo pedido —justo lo que el bug del conteo
    permitía crear— este AddConstraint falla. Revisar antes con:

        SELECT pedido_id, COUNT(*) FROM orden_reflejante
        WHERE activo GROUP BY pedido_id HAVING COUNT(*) > 1;

    y dar de baja (soft delete) las sobrantes antes de migrar.
    """

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('produccion', '0020_historicalordenproduccion_and_more'),
        ('ventas', '0040_cotizacion_tipo_pedido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ordenesreflejante',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('pedido',), name='uq_orden_reflejante_activa_por_pedido'),
        ),
    ]
