# Generated by Django 6.0.5 on 2026-08-03 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Índices únicos parciales: una sola OB / OCM activa por pedido.

    Gemelas de ``uq_orden_reflejante_activa_por_pedido`` (migración 0021).

    OJO al aplicar sobre datos existentes: si ya hay dos o más órdenes con
    ``activo=True`` para el mismo pedido —lo que el bug del conteo permitía
    crear— el AddConstraint correspondiente falla. Revisar antes con:

        SELECT pedido_id, COUNT(*) FROM orden_bordado
        WHERE activo GROUP BY pedido_id HAVING COUNT(*) > 1;

        SELECT pedido_id, COUNT(*) FROM orden_corte_manga
        WHERE activo GROUP BY pedido_id HAVING COUNT(*) > 1;

    y dar de baja (soft delete) las sobrantes antes de migrar.
    """

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('produccion', '0021_orden_reflejante_unica_activa_por_pedido'),
        ('ventas', '0040_cotizacion_tipo_pedido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ordenesbordado',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('pedido',), name='uq_orden_bordado_activa_por_pedido'),
        ),
        migrations.AddConstraint(
            model_name='ordenescortemanga',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('pedido',), name='uq_orden_corte_manga_activa_por_pedido'),
        ),
    ]
