# Generated by Django 6.0.6 on 2026-08-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0022_orden_bordado_ocm_unica_activa_por_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenbordadodetalle',
            name='bordado_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
