# Generated by Django 6.0.6 on 2026-08-05 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0023_ordenbordadodetalle_bordado_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenbordadodetalle',
            name='bordado_config',
        ),
    ]
