# Generated by Django 6.0.6 on 2026-08-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0024_remove_ordenbordadodetalle_bordado_config'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ordenescortemanga',
            name='uq_orden_corte_manga_activa_por_pedido',
        ),
        migrations.RemoveConstraint(
            model_name='ordenesreflejante',
            name='uq_orden_reflejante_activa_por_pedido',
        ),
    ]
