# Generated by Django 6.0.5 on 2026-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0026_remove_ordenesbordado_uq_orden_bordado_activa_por_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenbordadodetalle',
            name='configuracion',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenreflejantedetalle',
            name='configuracion',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
