# Generated by Django 6.0.6 on 2026-08-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0027_ordenbordadodetalle_configuracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordadoavances',
            name='puntadas_realizadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordenesbordado',
            name='maquina_asignada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
