# Generated by Django 6.0.6 on 2026-08-18 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0028_bordadoavances_puntadas_realizadas_and_more'),
        ('ventas', '0040_cotizacion_tipo_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordadoavances',
            name='orden_bordado_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produccion.ordenbordadodetalle'),
        ),
        migrations.AddField(
            model_name='bordadoavances',
            name='pedido_detalle_talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.pedidodetalletalla'),
        ),
    ]
