# Generated by Django 6.0.6 on 2026-08-21 14:01

from django.db import migrations, models


def remapear_estatus_bordado_forward(apps, schema_editor):
    """Remapea valores legacy del enum EstatusBordado a los nuevos ENTEROS.

    Mapeo semántico (antes → ahora):
      1 PENDIENTE   → 1 SIN_TRABAJAR   (igual significado)
      2 PREPARACION → 2 PROGRAMADO    (igual)
      3 BORDANDO    → 5 BORDANDO      (cambio de posición)
      4 REVISION    → 6 DETENIDO      (revisión se pausa hasta autorizar = detenido)
      5 COMPLETADO  → 7 FINALIZADO    (sinónimo)
      6 DETENIDO    → 6 DETENIDO      (sin cambio)
      7 CANCELADO   → 8 CANCELADO_LEGACY (valor nuevo legacy, no visible en UI)

    No se tocan las restricciones de integridad; el atributo sigue siendo
    IntegerField, sólo se traducen los valores para que el display coincida
    con el nuevo enum (Choices) y no se malinterpreten registros antiguos.
    """
    OrdenesBordado = apps.get_model('produccion', 'OrdenesBordado')

    # (1 → 1) y (2 → 2) y (6 → 6) quedan igual; sólo actualizamos los que cambian:
    remapeos = [
        (3, 5),   # BORDANDO legacy → BORDANDO nuevo (5)
        (4, 6),   # REVISION legacy → DETENIDO nuevo (6)
        (5, 7),   # COMPLETADO legacy → FINALIZADO nuevo (7)
        (7, 8),   # CANCELADO legacy → CANCELADO_LEGACY (8)
    ]
    for viejo, nuevo in remapeos:
        (
            OrdenesBordado.objects
            .filter(estatus_bordado=viejo)
            .update(estatus_bordado=nuevo)
        )


def remapear_estatus_bordado_backward(apps, schema_editor):
    """Rollback inverso para `migrate backwards`."""
    OrdenesBordado = apps.get_model('produccion', 'OrdenesBordado')
    remapeos = [
        (5, 3),
        (6, 4),   # nota: los Detenido originales (6) pasan a REVISIÓN legacy en
                  # rollback; al re-aplicar forward regresan a 6. Colisión benigna
                  # porque la semántica de REVISIÓN/DETENIDO legacy es cercana y
                  # en producción no solemos revertir migraciones de datos.
        (7, 5),
        (8, 7),
    ]
    for viejo, nuevo in remapeos:
        (
            OrdenesBordado.objects
            .filter(estatus_bordado=viejo)
            .update(estatus_bordado=nuevo)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0029_bordadoavances_orden_bordado_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordadoavances',
            name='puntadas_por_pieza',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bordadoavances',
            name='puntadas_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordenesbordado',
            name='proveedor_externo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(
            remapear_estatus_bordado_forward,
            remapear_estatus_bordado_backward,
        ),
        migrations.AlterField(
            model_name='ordenesbordado',
            name='estatus_bordado',
            field=models.IntegerField(choices=[(1, 'Sin trabajar'), (2, 'Programado'), (3, 'Ponchado'), (4, 'Arreglo'), (5, 'Bordando'), (6, 'Detenido'), (7, 'Finalizado'), (8, 'Cancelado (legacy)')], default=1),
        ),
    ]
