# Generated by Django 6.0.6 on 2026-08-21 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0030_bordadoavances_puntadas_por_pieza_and_more'),
        ('terceros', '0015_alter_historicalproveedor_fax_alter_proveedor_fax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenesbordado',
            name='proveedor_externo',
        ),
        migrations.AddField(
            model_name='ordenesbordado',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_bordado_proveedor', to='terceros.proveedor'),
        ),
    ]
