# Generated by Django 6.0.6 on 2026-08-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0031_remove_ordenesbordado_proveedor_externo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenbordadodetalle',
            name='descripcion_servicio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenbordadodetalle',
            name='tipo_servicio_bordado',
            field=models.CharField(choices=[('Plano', 'Bordado Plano'), ('3D', 'Bordado 3D (Puff)'), ('Chenille', 'Chenille / Toalla'), ('Aplicacion', 'Aplicación / Parche'), ('Reflectante', 'Hilo Reflectante'), ('Metalico', 'Hilo Metálico'), ('Combinado', 'Combinado (2+ técnicas)'), ('Otro', 'Otro (ver descripción)')], default='Plano', max_length=40),
        ),
    ]
