# Generated by Django 6.0.6 on 2026-08-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0032_ordenbordadodetalle_descripcion_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenbordadodetalle',
            name='tipos_servicio',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
