# Generated by Django 6.0.4 on 2026-09-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0033_ordenbordadodetalle_tipos_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordenproduccion',
            name='fecha_entrega_estimada',
            field=models.DateField(blank=True, help_text='Fecha estimada de entrega/resurtido, capturada por producción (mismo criterio que OrdenCompra.fecha_entrega_estimada).', null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_entrega_estimada',
            field=models.DateField(blank=True, help_text='Fecha estimada de entrega/resurtido, capturada por producción (mismo criterio que OrdenCompra.fecha_entrega_estimada).', null=True),
        ),
    ]
