# Generated by Django 6.0.4 on 2026-09-29 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0034_historicalordenproduccion_fecha_entrega_estimada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccionRutaCritica',
            fields=[
                ('op', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ruta_critica', serialize=False, to='produccion.ordenproduccion')),
                ('fecha_liberacion_paquete_tecnico', models.DateField(blank=True, null=True)),
                ('estatus_paquete_tecnico', models.CharField(blank=True, choices=[('actualizada', 'Actualizada'), ('nueva', 'Nueva'), ('espera_muestra', 'En espera de muestra')], max_length=20, null=True)),
                ('existencia_tela', models.BooleanField(default=False)),
                ('fecha_existencia_tela', models.DateTimeField(blank=True, null=True)),
                ('sin_existencia_tela', models.BooleanField(default=False)),
                ('fecha_sin_existencia_tela', models.DateTimeField(blank=True, null=True)),
                ('existencia_avios', models.BooleanField(default=False)),
                ('fecha_existencia_avios', models.DateTimeField(blank=True, null=True)),
                ('sin_existencia_avios', models.BooleanField(default=False)),
                ('fecha_sin_existencia_avios', models.DateTimeField(blank=True, null=True)),
                ('fecha_real_surtido_telas', models.DateField(blank=True, null=True)),
                ('fecha_real_surtido_avios', models.DateField(blank=True, null=True)),
                ('corte_externo', models.BooleanField(default=False)),
                ('comentarios_telas_avios', models.TextField(blank=True, null=True)),
                ('kit_completo', models.BooleanField(default=False)),
                ('fecha_embarque_materia_prima', models.DateField(blank=True, null=True)),
                ('fecha_trazo', models.DateField(blank=True, null=True)),
                ('fecha_real_corte', models.DateField(blank=True, null=True)),
                ('cantidad_real_corte', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('corte_recibido', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ruta Crítica de Orden de Producción',
                'verbose_name_plural': 'Rutas Críticas de Órdenes de Producción',
                'db_table': 'ordenes_produccion_ruta_critica',
            },
        ),
    ]
