# Generated by Django 6.0.5 on 2026-10-05 13:25

import django.contrib.postgres.indexes
import django.db.models.functions.text
import nucleo.indices
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0035_ordenproduccionrutacritica'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ordenesbordado',
            index=nucleo.indices.GinIndexSoloPostgres(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('folio_bordado'), name='gin_trgm_ops'), name='orden_bordado_folio_up_trgm'),
        ),
    ]
