# Generated by Django 6.0.5 on 2026-10-02 15:23

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations

from nucleo.migration_operations import AddIndexSoloPostgres


# Índice GIN trigram de expresión ``UPPER(folio_bordado)`` para el ``icontains``
# del buscador global. Ver ``AddIndexSoloPostgres`` para el porqué de la operación propia.


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('produccion', '0035_ordenproduccionrutacritica'),
        ('terceros', '0017_indices_busqueda_upper'),
        ('ventas', '0048_indices_busqueda_upper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexSoloPostgres(
            model_name='ordenesbordado',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('folio_bordado'), name='gin_trgm_ops'), name='orden_bordado_folio_up_trgm'),
        ),
    ]
