# Generated by Django 6.0.5 on 2026-10-05 17:16

import django.contrib.postgres.indexes
import django.db.models.functions.text
import nucleo.indices
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0036_orden_bordado_folio_upper'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ordenesreflejante',
            index=nucleo.indices.GinIndexSoloPostgres(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('folio_reflejante'), name='gin_trgm_ops'), name='orden_refl_folio_up_trgm'),
        ),
    ]
