# Generated by Django 6.0.7 on 2026-10-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0038_orden_corte_manga_folio_upper'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccionrutacritica',
            name='fecha_kit_completo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccionrutacritica',
            name='fecha_llegada_centro_confeccion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
