# Generated by Django 6.0.2 on 2026-03-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_direccioncliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccioncliente',
            options={'verbose_name': 'Direccion Cliente', 'verbose_name_plural': 'Direcciones Clientes'},
        ),
        migrations.AlterModelTable(
            name='direccioncliente',
            table='direcciones_cliente',
        ),
    ]
