# Generated by Django 6.0.2 on 2026-03-06 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0009_seriefolio_incluir_anio_seriefolio_reiniciar_anual_and_more'),
        ('terceros', '0003_alter_direccioncliente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccioncliente',
            name='activo',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='direccioncliente',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='terceros.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direccioncliente',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_clientes', to='nucleo.empresa'),
            preserve_default=False,
        ),
    ]
