# Generated by Django 6.0.2 on 2026-03-13 20:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('terceros', '0004_alter_direccioncliente_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codigo',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_principal',
            field=models.CharField(default='default', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dias_credito',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(default='default@mail.com', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='moneda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='nucleo.moneda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(default='default', max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='sat_forma_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='nucleo.satformapago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='sat_metodo_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='nucleo.satmetodopago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='sat_regimen_fiscal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='nucleo.satregimenfiscal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(default='3333333333', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
