# Generated by Django 6.0.2 on 2026-03-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('terceros', '0006_transportista'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(default='default', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(default='def', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(default='default', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(default='default', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_fiscal',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='default', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='giro_empresarial',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(default='default', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sat_regimen_fiscal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='nucleo.satregimenfiscal'),
            preserve_default=False,
        ),
    ]
