# Generated by Django 6.0.2 on 2026-03-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0007_cliente_ciudad_cliente_codigo_postal_cliente_colonia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
