# Generated by Django 6.0.2 on 2026-03-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0008_cliente_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccioncliente',
            name='celular_envio',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccioncliente',
            name='ciudad_envio',
            field=models.CharField(default='default', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccioncliente',
            name='codigo_postal',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccioncliente',
            name='colonia_envio',
            field=models.CharField(default='default', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccioncliente',
            name='destinatario',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccioncliente',
            name='direccion_envio',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccioncliente',
            name='empresa_envio',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccioncliente',
            name='estado_envio',
            field=models.CharField(default='default', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccioncliente',
            name='referencias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='direccioncliente',
            name='telefono_envio',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
