# Generated by Django 5.2 on 2026-03-25 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0009_direccioncliente_celular_envio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='vendedores',
            field=models.ManyToManyField(blank=True, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
