# Generated by Django 6.0.5 on 2026-06-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0011_alter_cliente_ciudad_alter_cliente_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='aplicar_a',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='colonia',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuenta_contable',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fax',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_ultima_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_ultimo_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='lista_precios',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='observaciones',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='plazo_dias',
            field=models.PositiveIntegerField(default=0, help_text='Plazo de crédito acordado con el proveedor.'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='plazo_real_dias',
            field=models.PositiveIntegerField(default=0, help_text='Promedio real de días utilizados para pagar.'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='saldo_acumulado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='saldo_anterior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo',
            field=models.CharField(choices=[('General', 'General'), ('Compras', 'Compras'), ('Impuestos', 'Impuestos'), ('Datos Bancarios', 'Datos Bancarios'), ('Varios', 'Varios'), ('Produccion', 'Produccion')], default='General', max_length=50),
        ),
    ]
