# Generated by Django 6.0.5 on 2026-08-28 21:35

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('terceros', '0015_alter_historicalproveedor_fax_alter_proveedor_fax'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cliente',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nombre'], name='clientes_nombre_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=django.contrib.postgres.indexes.GinIndex(fields=['razon_social'], name='clientes_razon_social_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=django.contrib.postgres.indexes.GinIndex(fields=['correo'], name='clientes_correo_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
