# Generated by Django 6.0.5 on 2026-10-05 13:25

import django.contrib.postgres.indexes
import django.db.models.functions.text
import nucleo.indices
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0016_cliente_clientes_nombre_trgm_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_nombre_trgm',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_razon_social_trgm',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_correo_trgm',
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=nucleo.indices.GinIndexSoloPostgres(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('nombre'), name='gin_trgm_ops'), name='clientes_nombre_upper_trgm'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=nucleo.indices.GinIndexSoloPostgres(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('razon_social'), name='gin_trgm_ops'), name='clientes_rsocial_upper_trgm'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=nucleo.indices.GinIndexSoloPostgres(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('correo'), name='gin_trgm_ops'), name='clientes_correo_upper_trgm'),
        ),
    ]
