# Generated by Django 6.0.5 on 2026-10-02 15:11

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations

from nucleo.migration_operations import AddIndexSoloPostgres


# Sustituye los GIN trigram v1 sobre la columna cruda —que ningún lookup del ORM
# puede usar: Django emite ``UPPER("col"::text) LIKE UPPER(%s)``— por índices de
# expresión sobre ``UPPER(col)``. Ver ``AddIndexSoloPostgres`` para el porqué de
# la operación propia.


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('terceros', '0016_cliente_clientes_nombre_trgm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_nombre_trgm',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_razon_social_trgm',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_correo_trgm',
        ),
        AddIndexSoloPostgres(
            model_name='cliente',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('nombre'), name='gin_trgm_ops'), name='clientes_nombre_upper_trgm'),
        ),
        AddIndexSoloPostgres(
            model_name='cliente',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('razon_social'), name='gin_trgm_ops'), name='clientes_rsocial_upper_trgm'),
        ),
        AddIndexSoloPostgres(
            model_name='cliente',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('correo'), name='gin_trgm_ops'), name='clientes_correo_upper_trgm'),
        ),
    ]
