# Generated by Django 6.0.5 on 2026-06-08 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('terceros', '0011_alter_cliente_ciudad_alter_cliente_codigo_postal_and_more'),
        ('ventas', '0038_alter_cotizacion_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='nucleo.empresa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='ventas.pedido')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='nucleo.sucursal')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='terceros.transportista')),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
                'db_table': 'envios',
            },
        ),
        migrations.CreateModel(
            name='EnvioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envio_detalle', to='ventas.entrega')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envio_detalle', to='logistica.envio')),
            ],
            options={
                'verbose_name': 'Envio Detalle',
                'verbose_name_plural': 'Envios Detalles',
                'db_table': 'envio_detalle',
            },
        ),
    ]
