# Generated by Django 6.0.2 on 2026-03-03 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0004_alter_tipoproducto_codigo'),
        ('inventarios', '0007_alter_movimientoinventariodetalle_options_and_more'),
        ('nucleo', '0009_seriefolio_incluir_anio_seriefolio_reiniciar_anual_and_more'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.moneda')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.proveedor')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.sucursal')),
            ],
            options={
                'verbose_name': 'Orden Compra',
                'verbose_name_plural': 'Ordenes Compra',
                'db_table': 'ordenes_compra',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Orden Compra Detalle',
                'verbose_name_plural': 'Ordenes Compra Detalle',
                'db_table': 'orden_compra_detalle',
            },
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.almacen')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.ordencompra')),
            ],
            options={
                'verbose_name': 'Recepcion',
                'verbose_name_plural': 'Recepciones',
                'db_table': 'recepciones',
            },
        ),
        migrations.CreateModel(
            name='RecepcionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.lote')),
                ('orden_compra_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.ordencompradetalle')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.recepcion')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.serie')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.ubicacion')),
            ],
            options={
                'verbose_name': 'Recepcion Detalle',
                'verbose_name_plural': 'Recepciones Detalle',
                'db_table': 'recepcion_detalle',
            },
        ),
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.sucursal')),
            ],
            options={
                'verbose_name': 'Requisición',
                'verbose_name_plural': 'Requisiciones',
                'db_table': 'requisiciones',
            },
        ),
        migrations.CreateModel(
            name='CotizacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.moneda')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.proveedor')),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.requisicion')),
            ],
            options={
                'verbose_name': 'Cotización Proveedor',
                'verbose_name_plural': 'Cotizaciones Proveedor',
                'db_table': 'cotizaciones_proveedor',
            },
        ),
        migrations.CreateModel(
            name='RequisicionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.requisicion')),
            ],
            options={
                'verbose_name': 'Requisición Detalle',
                'verbose_name_plural': 'Requisiciones Detalle',
                'db_table': 'requisicion_detalle',
            },
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='requisicion_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.requisiciondetalle'),
        ),
        migrations.CreateModel(
            name='CotizacionProveedorDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotizacion_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.cotizacionproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
                ('requisicion_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.requisiciondetalle')),
            ],
            options={
                'verbose_name': 'Cotización Proveedor Detalle',
                'verbose_name_plural': 'Cotizaciones Proveedor Detalle',
                'db_table': 'cotizacion_proveedor_detalle',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.empresa')),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.requisicion')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.sucursal')),
            ],
            options={
                'verbose_name': 'Solicitud Compra',
                'verbose_name_plural': 'Solicitudes Compra',
                'db_table': 'solicitudes_compra',
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='solicitud_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.solicitudcompra'),
        ),
        migrations.CreateModel(
            name='SolicitudCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
                ('requisicion_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.requisiciondetalle')),
                ('solicitud_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.solicitudcompra')),
            ],
            options={
                'verbose_name': 'Solicitud Compra Detalle',
                'verbose_name_plural': 'Solicitudes Compra Detalle',
                'db_table': 'solicitud_compra_detalle',
            },
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='solicitud_compra_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.solicitudcompradetalle'),
        ),
    ]
