# Generated by Django 6.0.2 on 2026-03-13 21:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('terceros', '0005_proveedor_activo_proveedor_codigo_and_more'),
        ('ventas', '0003_pedido_tipo_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'Borrador'), (2, 'Por autorizar'), (3, 'Autorizada'), (4, 'Parcialmente recibida'), (5, 'Recibida'), (6, 'Cancelada')], default=1),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_autorizacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_entrega_estimada',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_oc',
            field=models.DateField(default='2026-03-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='folio',
            field=models.CharField(default='default', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='impuestos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='ventas.pedido'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='referencia',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcion',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='nucleo.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcion',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'Borrador'), (2, 'Recibida'), (3, 'Parcial'), (4, 'En calidad'), (5, 'Cerrada'), (6, 'Cancelada')], default=1),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='factura_referencia',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='fecha_recepcion',
            field=models.DateTimeField(default='2026-03-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcion',
            name='folio',
            field=models.CharField(default='default', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='terceros.proveedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcion',
            name='remision',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='nucleo.sucursal'),
            preserve_default=False,
        ),
    ]
