# Generated by Django 6.0.2 on 2026-03-13 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_ordencompra_activo_ordencompra_created_at_and_more'),
        ('terceros', '0006_transportista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='transportista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='terceros.transportista'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
