# Generated by Django 6.0.4 on 2026-05-07 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_recepcion_transportista_recepcion_updated_at_and_more'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='a_cuenta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='flete',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='gran_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='seguros',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='tipo',
            field=models.CharField(default='ODC', max_length=20),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='total_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='total_piezas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='piezas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra_detalle', to='nucleo.sucursal'),
            preserve_default=False,
        ),
    ]
