# Generated by Django 5.2 on 2026-05-11 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_ordencompra_a_cuenta_ordencompra_fecha_vencimiento_and_more'),
        ('terceros', '0011_alter_cliente_ciudad_alter_cliente_codigo_postal_and_more'),
        ('ventas', '0034_cotizacionservicioextra_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='folio',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='ventas.pedido'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='terceros.proveedor'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='solicitud_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.solicitudcompra'),
        ),
    ]
