# Generated by Django 6.0.5 on 2026-06-11 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_ordencompra_folio_alter_ordencompra_pedido_and_more'),
        ('inventarios', '0012_movimientoinventario_op_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepciondetalle',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.lote'),
        ),
        migrations.AlterField(
            model_name='recepciondetalle',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.serie'),
        ),
    ]
