# Generated by Django 5.2 on 2026-06-12 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_alter_recepciondetalle_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompradetalle',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordencompradetalle',
            name='requisicion_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.requisiciondetalle'),
        ),
        migrations.AlterField(
            model_name='ordencompradetalle',
            name='solicitud_compra_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.solicitudcompradetalle'),
        ),
    ]
