# Generated by Django 5.2 on 2026-06-15 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_producto_tipo'),
        ('compras', '0007_alter_ordencompradetalle_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepciondetalle',
            name='cantidad_recibida',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='recepciondetalle',
            name='producto_variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.productovariante'),
        ),
    ]
