# Generated by Django 5.2 on 2026-06-17 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_recepciondetalle_cantidad_recibida_and_more'),
        ('inventarios', '0013_existencia_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepciondetalle',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.ubicacion'),
        ),
    ]
