# Generated by Django 5.2 on 2026-07-03 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_alter_recepciondetalle_ubicacion'),
        ('produccion', '0019_ordenproduccion_cerrar_orden'),
        ('terceros', '0013_cliente_celular_cliente_clave_cliente_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='op',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='tipo_origen',
            field=models.CharField(choices=[('OC', 'Orden de compra'), ('OP', 'Orden de produccion')], default='OC', max_length=2),
        ),
        migrations.AddField(
            model_name='recepciondetalle',
            name='orden_produccion_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenproducciondetalle'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.ordencompra'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='terceros.proveedor'),
        ),
        migrations.AlterField(
            model_name='recepciondetalle',
            name='orden_compra_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.ordencompradetalle'),
        ),
    ]
