# Generated by Django 6.0.4 on 2026-07-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_historicalcotizacionproveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalordencompra',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'Borrador'), (2, 'Pendiente a confirmar'), (3, 'Autorizada'), (4, 'Parcialmente recibida'), (5, 'Recibida'), (6, 'Cancelada')], default=1),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'Borrador'), (2, 'Pendiente a confirmar'), (3, 'Autorizada'), (4, 'Parcialmente recibida'), (5, 'Recibida'), (6, 'Cancelada')], default=1),
        ),
    ]
