# Generated by Django 6.0.6 on 2026-07-27 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_historicalcategoriaproducto_historicalproducto_and_more'),
        ('compras', '0012_alter_historicalordencompra_estatus_and_more'),
        ('inventarios', '0019_inventario_reservas_almacen_and_more'),
        ('nucleo', '0014_remove_departamento_departament_empresa_4c7874_idx_and_more'),
        ('produccion', '0020_historicalordenproduccion_and_more'),
        ('terceros', '0015_alter_historicalproveedor_fax_alter_proveedor_fax'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionRFIDEncuadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_origen', models.CharField(choices=[('OC', 'Orden de compra'), ('OP', 'Orden de produccion')], default='OC', max_length=2)),
                ('serie_codigo', models.CharField(default='RC', max_length=2)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('remision', models.CharField(blank=True, max_length=50, null=True)),
                ('factura_referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_encuadres_recepcion', to='inventarios.almacen')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_encuadres_recepcion', to='nucleo.empresa')),
                ('op', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid_encuadres', to='produccion.ordenproduccion')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid_encuadres', to='compras.ordencompra')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid_encuadres_recepcion', to='terceros.proveedor')),
                ('recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_encuadres', to='compras.recepcion')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_encuadres_recepcion', to='nucleo.sucursal')),
                ('transportista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid_encuadres_recepcion', to='terceros.transportista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_encuadres_recepcion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recepcion RFID Encuadre',
                'verbose_name_plural': 'Recepciones RFID Encuadre',
                'db_table': 'recepcion_rfid_encuadre',
            },
        ),
        migrations.CreateModel(
            name='RecepcionRFIDLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tag', models.CharField(max_length=120)),
                ('cantidad_leida', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encuadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='compras.recepcionrfidencuadre')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.lote')),
                ('orden_compra_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid_lecturas_recepcion', to='compras.ordencompradetalle')),
                ('orden_produccion_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid_lecturas_recepcion', to='produccion.ordenproducciondetalle')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
                ('producto_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.productovariante')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.serie')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.ubicacion')),
            ],
            options={
                'verbose_name': 'Recepcion RFID Lectura',
                'verbose_name_plural': 'Recepciones RFID Lecturas',
                'db_table': 'recepcion_rfid_lectura',
                'constraints': [models.UniqueConstraint(fields=('encuadre', 'codigo_tag'), name='uq_recepcion_rfid_lectura_encuadre_tag')],
            },
        ),
    ]
