# Generated by Django 6.0.6 on 2026-08-11 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_recepcionrfidencuadre_recepcionrfidlectura'),
        ('hr', '0001_initial'),
        ('terceros', '0015_alter_historicalproveedor_fax_alter_proveedor_fax'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('aprobada_condicion', 'Aprobada con condiciones')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calidad_inspecciones', to='hr.empleado')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calidad_inspecciones', to='compras.recepcion')),
            ],
            options={
                'verbose_name': 'Calidad Inspección',
                'verbose_name_plural': 'Calidad Inspecciones',
                'db_table': 'calidad_inspecciones',
            },
        ),
        migrations.CreateModel(
            name='CalidadInspeccionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_inspeccionada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_aprobada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_rechazada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('resultado', models.TextField(choices=[('cuarentena', 'Cuarentena'), ('liberado', 'Liberado'), ('concesion_cc', 'Concesión Control de Calidad'), ('concesion lazzar', 'Concesión lazzar'), ('rechazo', 'Rechazo')], default='aprobado', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('calidad_inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.calidadinspeccion')),
                ('recepcion_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calidad_inspecciones', to='compras.recepciondetalle')),
            ],
            options={
                'verbose_name': 'Calidad Inspección Detalle',
                'verbose_name_plural': 'Calidad Inspecciones Detalle',
                'db_table': 'calidad_inspeccion_detalle',
            },
        ),
        migrations.CreateModel(
            name='EnvioProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(blank=True, max_length=100)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('preparando', 'Preparando'), ('en_transito', 'En tránsito'), ('entregado', 'Entregado'), ('retrasado', 'Retrasado'), ('cancelado', 'Cancelado')], default='preparando', max_length=20)),
                ('costo_envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('oc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_proveedor', to='compras.ordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_proveedor', to='terceros.proveedor')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_proveedor', to='terceros.transportista')),
            ],
            options={
                'verbose_name': 'Envio Proveedor',
                'verbose_name_plural': 'Envios Proveedor',
                'db_table': 'envios_proveedor',
            },
        ),
    ]
