# Generated by Django 6.0.5 on 2026-09-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_calidadinspeccion_calidadinspecciondetalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordencompra',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
